laravel/passport

.travis.yml
=> Use --prefer-dist option

src/Bridge/AccessToken.php
=> Fix a docblock

composer.json
=> Add missing composer require

src/Bridge/AuthCodeRepository.php, src/Http/Controllers/ClientController.php, src/Http/Controllers/PersonalAccessTokenController.php, src/Passport.php, src/PersonalAccessTokenFactory.php, tests/ApiTokenCookieFactoryTest.php, tests/ApproveAuthorizationControllerTest.php, tests/AuthorizedAccessTokenControllerTest.php, tests/DenyAuthorizationControllerTest.php
=> Remove unused imports

src/ClientRepository.php
Basic functionality to allow client secrets to be reset in the case of a leaked secret key etc.
=> Add method to reset client secret

src/HasApiTokens.php
Fix some comments and docblocks.
=> Fix some comments and docblocks.

src/Console/ClientCommand.php
=> Reformat command signature

src/Bridge/UserRepository.php, src/Http/Controllers/ApproveAuthorizationController.php, tests/ApproveAuthorizationControllerTest.php
=> Remove useless imports

src/ClientRepository.php, src/Http/Middleware/CheckForAnyScope.php, src/Http/Middleware/CheckScopes.php
=> Fix docblocks spacing

src/AuthCode.php, src/Client.php, src/Token.php
=> Add casts and dates.

src/AuthCode.php, src/Client.php, src/PersonalAccessClient.php, src/Token.php
=> Fix model docblocks

src/Console/ClientCommand.php
=> Remove useless variable

src/Bridge/UserRepository.php
Prevent `Trying to get property of non-object` if email doesn't exist in user table
=> Add null user check

.travis.yml
=> Disable xdebug

src/Http/Middleware/CreateFreshApiToken.php
First ever pull request. Hope I'm doing this right. :)
=> Update comment to include $response

composer.json
Bump `symfony/psr-http-message-bridge` version
=> Bump symfony/psr-http-message-bridge version

resources/assets/js/components/AuthorizedClients.vue, resources/assets/js/components/Clients.vue, resources/assets/js/components/PersonalAccessTokens.vue
Makes the Passport components compatible with Vue.js 2. 
I've also [submitted a PR for Laravel](https://github.com/laravel/laravel/pull/3979) that provides Vue.js 2 compatibility.
=> Update for Vue.js 2.0.x

src/Http/Middleware/CreateFreshApiToken.php
I missed the guard handling in the cookie factory. Now it works.
=> Added guard handling to cookie handling too

src/Http/Middleware/CheckClientCredentials.php, tests/CheckClientCredentialsTest.php
Resubmitting to 1.0 as requested.
This PR adds unit tests for Check Client Credentials middleware and adds scopes check to same.
=> Credential grant scopes

src/PassportServiceProvider.php
This PR fixes a security issue [outlined](https://github.com/laravel/passport/issues/85#issuecomment-256615353) by @doublebit:
> This is a serious problem. Let's say I have a SPA and I have two tabs opened on the browser. I logout in one of them and step away from the computer. This basically provides full access to anyone who sits next to me and doesn't refresh the other tab.
It is important to delete the `laravel_token` cookie on logout, otherwise we are still able to use the application in other tabs or by opening tabs from the browser history (Ctrl+Alt+T or just the back button).
See #85 for further discussion.
=> Delete the laravel_token cookie on logout

src/Bridge/AccessTokenRepository.php
=> Sets search mode to boolean for revoked field

src/Http/Controllers/AccessTokenController.php, src/Passport.php
see https://github.com/laravel/passport/pull/176#issuecomment-259957727
how about something like this?
=> static setter for revoking other tokens

src/Token.php
Relation will help to get `User` by token
```php
\Laravel\Passport\Token::find($token)->user
```
=> Added user relationship in token model.

src/RouteRegistrar.php
To prevent brute forcing that endpoint.
=> Rate Limit the /oauth/token route

src/Bridge/UserRepository.php, src/Token.php
users provider was set statically in the code. Changed to use one specified for api configuration
=> Customisable Authentication Model

src/Bridge/ScopeRepository.php
Looks like PR #200 from 1.0 was not merged into 2.0.
=> [2.0] Personal access tokens can't get "*" scope.

composer.json, resources/assets/js/components/Clients.vue, resources/assets/js/components/PersonalAccessTokens.vue
As per the documentation at https://github.com/mzabriskie/axios#handling-errors axios puts the response in an error object on .catch()
=> Fix error display, use axios error response correctly.

src/Passport.php, src/RouteRegistrar.php
enable routes namespace to override and `/oauth` as default prefix, make it possible to user who whants `/anything/[*]` routes
=> configurable route options

src/Http/Controllers/AuthorizationController.php, src/TokenRepository.php, tests/AuthorizationControllerTest.php
I have copied the missing lines of codes from version 1.x 
https://github.com/laravel/passport/issues/273
=> PR for #273 - Bypass auth screen if we already have a token

src/Http/Controllers/AuthorizationController.php, src/TokenRepository.php, tests/AuthorizationControllerTest.php
Fix bypass auth screen when we have a token, merge from master branch to 2.0
=> Update branch 2.0 with last fix on bypass screen when token exist

src/Http/Controllers/ScopeController.php
PHPDoc return should be Collection
=> Update ScopeController.php PHPDoc @return

src/Http/Middleware/CheckClientCredentials.php
Fixes spacing issues and adds missing docblock param.
=> Spacing and docblocks

src/Passport.php
Updates the docblocks description, adds a missing parameter and fixes incorrect return type.
=> Update route() docblock

src/TokenRepository.php
https://github.com/laravel/passport/issues/387
=> fix revoke access token when token is deleted

src/Bridge/RefreshTokenRepository.php
I noticed that there is not a single unit test for RefreshTokens. I would have added one, but I'm not really sure how I would approach mocking the `$database` parameter of `RefreshTokenRepository::__construct()` best, so I omitted that.
This PR fixes a security issue, I opted for a public pull request, because the issue already has been reported publicly in #389.
------
This patch makes sure that RefreshTokenRepository::isRefreshTokenRevoked()
returns false if:
- The refresh token is completely deleted
- The refresh token is revoked
- The associated access token is revoked
The last one ensures that refresh tokens are invalidated if a user revokes
access he granted to an application.
Fixes #389
=> Fix revocal of refresh tokens

src/ClientRepository.php
=> Fix ClientRepository::revoked() for deleted clients

src/Bridge/UserRepository.php, src/Console/KeysCommand.php, src/Http/Controllers/AuthorizedAccessTokenController.php, src/Passport.php, src/RouteRegistrar.php, src/TokenRepository.php, tests/CheckClientCredentialsTest.php, tests/KeysCommandTest.php
=> [2.0] Some style fixes.

src/ApiTokenCookieFactory.php, src/Bridge/AccessTokenRepository.php, src/Bridge/FormatsScopesForStorage.php, src/Bridge/RefreshTokenRepository.php, src/ClientRepository.php, src/Console/KeysCommand.php, src/Events/RefreshTokenCreated.php, src/Guards/TokenGuard.php, src/Http/Controllers/AccessTokenController.php, src/Http/Controllers/ApproveAuthorizationController.php, src/Http/Controllers/AuthorizationController.php, src/Http/Controllers/AuthorizedAccessTokenController.php, src/Http/Controllers/ClientController.php, src/Http/Controllers/DenyAuthorizationController.php, src/Http/Controllers/HandlesOAuthErrors.php, src/Http/Controllers/PersonalAccessTokenController.php, src/Http/Controllers/RetrievesAuthRequestFromSession.php, src/Http/Controllers/TransientTokenController.php, src/Http/Middleware/CheckClientCredentials.php, src/Http/Middleware/CheckForAnyScope.php, src/Http/Middleware/CheckScopes.php, src/Http/Middleware/CreateFreshApiToken.php, src/PassportServiceProvider.php, src/PersonalAccessTokenFactory.php, src/PersonalAccessTokenResult.php, src/RouteRegistrar.php, src/TokenRepository.php
=> [2.0] Fix many docblocks.

src/ClientRepository.php
**Use case**: Single point of entry for cache implementation.
=> Reuse find() method on client repository

src/PassportServiceProvider.php
Resolving TopicRespository class via container to aid binding with different implementation.
=> Allow binding token repository instance

composer.json
=> [3.0] Some composer adjustments.

src/Bridge/Client.php
Split url by commas, oauth2-server support pass the redirect_uri array.
reference by thephpleague/oauth2-server#511
=> Support multiple redirect uri

src/Token.php
Need to know the result of resolve function result to proceed.
=> Returning revoke result

.travis.yml
In addition to laravel/framework#20329
=> Always remove xdebug

src/Passport.php
This PR would allow simpler syntax in tests as I've proposed in #618.
=> Passport::actingAs returns the user

composer.json
Hi,
I added the missing firebase 5.0 dependency which was already in 4.0.
=> Added firebase 5.0 as possible dependency

resources/assets/js/components/PersonalAccessTokens.vue
=> Add the loss row class

database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php, database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php, database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php, database/migrations/2016_06_01_000004_create_oauth_clients_table.php, database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
I was getting errors about this in my tests, which start with an empty database.
=> Use dropIfExists() instead of drop()

src/Guards/TokenGuard.php, src/Passport.php
Backport pull request #796 into laravel/passport 4.0
=> Backport pull request #796

src/PassportServiceProvider.php
The migrations were not publishable.
=> fix migrations tag publish

src/Client.php
- Added a method on the ``Client`` model to retrieve the user.
=> [7.0] Add user relationship to client model

src/RouteRegistrar.php
=> [7.0] Add names to routes for reusability

src/Bridge/AuthCodeRepository.php
- Changed the hardcoding of the "oauth_auth_codes" to get the table from the definable model
=> [7.0] Change auth code table to the model's table

src/TokenRepository.php
- Changed all `whereRevoked` to `where('revoked')`
=> [7.0] Made whereRevoked consistent (Taylor's way)

src/Console/ClientCommand.php, src/Console/InstallCommand.php, src/Console/KeysCommand.php
This PR cleans up the commands a bit. You can follow all of the changes by the commit messages.
=> [7.0] Cleanup commands

src/TokenRepository.php
=> [7.0] Remove dangling import

tests/AccessTokenControllerTest.php, tests/ApiTokenCookieFactoryTest.php, tests/ApproveAuthorizationControllerTest.php, tests/AuthorizationControllerTest.php, tests/AuthorizedAccessTokenControllerTest.php, tests/BridgeAccessTokenRepositoryTest.php, tests/BridgeClientRepositoryTest.php, tests/CheckClientCredentialsForAnyScopeTest.php, tests/CheckClientCredentialsTest.php, tests/ClientControllerTest.php, tests/DenyAuthorizationControllerTest.php, tests/PassportTest.php, tests/PersonalAccessTokenControllerTest.php, tests/PersonalAccessTokenFactoryTest.php, tests/TokenGuardTest.php, tests/TransientTokenControllerTest.php
Updates all references to objects in the test suite to imported namespaces.
=> [7.0] Import namespaces in test suite

.circleci/config.yml
Attempt at setting up a CircleCI build.
=> [7.0] Circleci

database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php, database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php, database/migrations/2016_06_01_000004_create_oauth_clients_table.php
=> [7.0] Use bigInteger column type for user_id columns

src/Bridge/AccessToken.php, src/Bridge/AccessTokenRepository.php, src/Bridge/Client.php, src/Bridge/ClientRepository.php, src/Bridge/UserRepository.php, src/ClientRepository.php, src/Http/Controllers/RetrievesAuthRequestFromSession.php, src/Http/Middleware/CheckClientCredentials.php, src/Http/Middleware/CheckClientCredentialsForAnyScope.php, src/Http/Middleware/CheckCredentials.php, src/Http/Middleware/CheckForAnyScope.php, src/Http/Middleware/CheckScopes.php, src/Http/Rules/RedirectRule.php, src/PassportServiceProvider.php, src/PersonalAccessTokenFactory.php, src/TokenRepository.php
This PR does:
- Format docblocks
- Remove unused import
- Change `private` to `protected`
=> [8.x] Format docs

composer.json, src/Guards/TokenGuard.php, src/Http/Controllers/AccessTokenController.php, src/Http/Controllers/ApproveAuthorizationController.php, src/Http/Controllers/AuthorizationController.php, src/Http/Controllers/HandlesOAuthErrors.php, src/Http/Middleware/CheckCredentials.php, src/PersonalAccessTokenFactory.php, tests/AccessTokenControllerTest.php, tests/ApproveAuthorizationControllerTest.php
Replace the deprecated Zend/Diactoros package with Laminas/Diactoros
=> [8.x] Replace deprecated package and namespaces

src/Http/Controllers/AuthorizedAccessTokenController.php, src/RefreshTokenRepository.php, tests/AuthorizedAccessTokenControllerTest.php
This will revoke all refresh tokens when their access tokens gets revoked.
=> [8.x] Revoke refresh tokens as well

src/Passport.php
This wasn't used anymore for quite a while it seems.
=> [9.x] Remove deprecated functionality

composer.json
Bump league server to the latest minor release.
=> [9.x] Bump league server dependency

UPGRADE.md
Clarify upgrade step when migrations weren't published.
Closes https://github.com/laravel/passport/issues/1264
=> [9.x] Update UPGRADE.md

tests/Feature/Console/HashCommand.php
A small typo in the name of this test.
=> correct test name

composer.json
Hi,
Guzzle v7 stable is out now.
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md
=> Allow guzzle v7

UPGRADE.md
=> [10.x] Upgrade guide

src/PassportServiceProvider.php
=> remove unnecessary return form service provider

src/PassportServiceProvider.php, tests/Feature/AccessTokenControllerTest.php
Small tweaks to ensure compatibility with `lcobucci/jwt` 3.4 and 4.0
=> Compatibility fix

src/Console/HashCommand.php, src/Console/InstallCommand.php, src/Console/KeysCommand.php
Fixed some output messages on the CLI. No breaking changes at all!
=> Fixed output typos under Commands.

UPGRADE.md
=> Passport v11 upgrade guide

src/Http/Controllers/AuthorizationController.php, tests/Unit/AuthorizationControllerTest.php
Related to #1389
As explained on #1567 and in addition to that, this PR adds support for `prompt=none` that causes the authorization server not display user consent screen; it will return an error if the user has not pre-configured consent for the requested scopes. It can be used to check for existing consent.
=> [11.x] Support disabling prompt when redirecting for authorization

src/Guards/TokenGuard.php
Tiny improvement to help IDEs and static analysis tools.
=> [11.x] Improve token guard return type

src/ClientRepository.php
=> [11.x] Update docblock

database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php, database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php, database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php, database/migrations/2016_06_01_000004_create_oauth_clients_table.php, database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
Please check https://github.com/laravel/laravel/pull/6010 for details about this pull request.
=> [11.x] Uses PHP Native Type Declarations 🐘

.gitattributes, .github/workflows/static-analysis.yml, composer.json, phpstan.neon.dist, src/Guards/TokenGuard.php
This pull request adds type checking to this repository.
=> [11.x] Adds type checking

src/Http/Controllers/AuthorizationController.php
On #1629 some types changed by mistake. any automated checking for this in future?
=> [11.x] Fix doc block types

composer.json, src/PassportServiceProvider.php, tests/Unit/PersonalAccessTokenFactoryTest.php
=> [11.x] Allow `lcobucci/jwt` v5 and cleaned up version constraints

src/ClientRepository.php, src/Console/ClientCommand.php, src/Console/InstallCommand.php
=> Revert "[11.x] Add Provider Guard to ClientRepository for Personal Access Clients"

composer.json, testbench.yaml, tests/Feature/AccessTokenControllerTest.php, tests/Feature/ActingAsTest.php, tests/Feature/KeysCommandTest.php, tests/Feature/PassportTestCase.php, workbench/app/Models/User.php, workbench/database/factories/UserFactory.php
=> Test Improvements

.github/workflows/static-analysis.yml, .github/workflows/tests.yml
Update actions/checkout to v4
[actions/checkout/releases/v4.0.0](https://github.com/actions/checkout/releases/tag/v4.0.0)
=> Update actions/checkout to v4

src/RefreshTokenRepository.php
=> Add return to revokeRefreshTokensByAccessTokenId method

src/Console/ClientCommand.php, src/Console/HashCommand.php, src/Console/InstallCommand.php, src/Console/KeysCommand.php, src/Console/PurgeCommand.php, tests/Feature/KeysCommandTest.php
Related to laravel/framework#50386
This PR:
* Makes running migrations and creating default clients optional when installing.
* Enhances CLI output by using console components.
=> [12.x] Enhance console commands
