laravel/passport

- .travis.yml
Don't test on hhvm sense  `ARRAY_FILTER_USE_BOTH` constant is not present. 
Or allow it to fail tests maybe?
> Don't test on hhvm

- src/Http/Controllers/RetrievesAuthRequestFromSession.php
- src/Http/Middleware/CreateFreshApiToken.php
- src/Passport.php
- src/PersonalAccessTokenFactory.php
- src/PersonalAccessTokenResult.php
- src/RouteRegistrar.php
- tests/AuthorizationControllerTest.php
- tests/AuthorizedAccessTokenControllerTest.php
- tests/ClientControllerTest.php
- tests/PersonalAccessTokenControllerTest.php
Apply some code formatting
---
Might be worth to enable styleci here
> Apply some code formatting

- src/HasApiTokens.php
If your model is named something other than Users it tries to use that name for the relation. 
For instance mine is called `App\Contact\Person` and it's trying to use `person_id` for queries instead of the `user_id` that is in the schema.
> explicitly set user_id as the field name for relations

- src/Bridge/UserRepository.php
Problem with primary key distinct to "id". Dont save user_id on oauth_access_tokens.
> Change identifier of user id by return of method getAuthIdentifier()

- composer.json
- src/Console/KeysCommand.php
- tests/KeysCommandTest.php
Sometimes the 'openssl' cli utility may not me available, especially on windows this may require some ceremony.
Updated this command to leverage phpseclib instead.
> Use phpseclib for generating keys

- src/Http/Middleware/CheckClientCredentials.php
- src/PassportServiceProvider.php
This grant type is useful to allow clients to access data that's not owned by a certain user, for example: searching tweets, listing supported countries, etc...
The PR implements a middleware that can be used to check for client credentials.
> Enable client credentials grant type

- resources/assets/js/components/PersonalAccessTokens.vue
The first checkbox in the Personal Access Token component can’t be checked.
`_.indexOf()` returns -1, not 0, if it wasn’t found.
My first PR, please tell me if I did something wrong 😳
> Fix first scope checkbox

- src/Bridge/AccessTokenRepository.php
- src/TokenRepository.php
- tests/BridgeAccessTokenRepositoryTest.php
- tests/PersonalAccessTokenFactoryTest.php
This replaces the usage of using the Database Connection in favor of TokenRepository which then calls `Token` directly.
A big benefit of this is so that Model events can be observed when creating Access Tokens.
I believe this would cover at least part of [Issue #77](https://github.com/laravel/passport/issues/77).
> Use Token model/repository when working with AccessTokenRepository

- src/Console/KeysCommand.php
- src/Passport.php
- src/PassportServiceProvider.php
- tests/KeysCommandTest.php
- tests/files/.gitignore
Adding the ability to load keys from a custom location:
```
Passport::loadKeysFrom('/var/http/path/to/files');
```
If not set, Passport will look for the keys inside `storage_path()` by default.
> Ability to load keys from a custom location

- src/Http/Middleware/CheckScopes.php
- tests/CheckScopesTest.php
Should this not throw AuthorizationException when the user doesn't have the required scopes as the user is authenticated but doesn't have the scope to access the route?
> Throw AuthorizationException if user doesn't have scope

- src/Bridge/AccessTokenRepository.php
Security bug:
per @parkershepherd:
Because the check in https://github.com/thephpleague/oauth2-server/blob/a798cfdc5d9989b3ee111a063ec49a84046d364a/src/AuthorizationValidators/BearerTokenValidator.php#L64 is essentially a blacklist instead of a whitelist, explicitly revoked tokens become usable again if the revoked entries are pruned. (also if someone was able to generate a valid JWT that didn't match any tokens in the DB, they would be treated as valid)
Intended behavior:
Only tokens explicitly stored in the DB should be valid (a non-revoked entry should exist in the oauth_access_tokens table)
Steps to reproduce
Generate a token
Verify token works on a route
Revoke token in the DB
Verify token results in an authentication error
Delete the token completely from the DB (i.e. …
> Don't validate tokens that have been pruned

- src/Http/Controllers/ClientController.php
- src/Http/Controllers/RetrievesAuthRequestFromSession.php
As discussed in #106, using `$request->user()->id` wont work when using a different primary key name instead of the default `id`.
Since Eloquent models have support for custom key names, we can simply check if we are dealing with an Eloquent model and use the `getKey()` helper instead.
Because we can change the user model using the `auth.php` config and thereby potentially also change the type, ie. not an Eloquent instance, we fallback on using `->id` to directly fetch the preferred default value.
@taylorotwell As requested on #107 now with a longer description.
> Added support for custom primary key names on user models, resolves: #106

- src/Console/ClientCommand.php
This fix adds the '=' to the name option of command signature to able to call it like:
```
php artisan passport:client --name="My Client Name"
```
Currently it throws the following exception:
```
[Symfony\Component\Console\Exception\RuntimeException]
The "--name" option does not accept a value.
```
> Fix the --name option on the ClientCommand

- src/Http/Middleware/CreateFreshApiToken.php
For using the CreateFreshApiToken middleware with multiple auth providers, the guards must set when it looks for the user.
> Added guard handling to CreateFreshApiToken

- src/ApiTokenCookieFactory.php
- src/Guards/TokenGuard.php
- src/Http/Middleware/CreateFreshApiToken.php
- src/Passport.php
Revised version of #139
As requested by @taylorotwell, I use `Passport::cookie()` instead of a configuration option to set the cookie name.
I would love to add some test cases, but calling `Passport::cookie('foo')` in one test also affects the cookie name for all later tests (even for other classes). Is there any good workaround for that problem, i.e. how to reset the `Passport` class static state after a test?
> Allow to configure ApiTokenCookie name (2)

- src/TokenRepository.php
`revoked` attribute is saved in boolean but searched by integer here. It breaks working with mongodb.
So replaced to boolean.
> Change revoked field to be searched by boolean

- src/Console/ClientCommand.php
When firing `php artisan passport:client --password` or `php artisan passport:client --personal`, the `client_id` and `client_secret` are now visible in the console.
This way you don't need to manually lookup the `id` and `secret` from the database.
> Shows the client secret and id in the console

- src/Bridge/AccessTokenRepository.php
- src/Bridge/FormatsScopesForStorage.php
- tests/BridgeAccessTokenRepositoryTest.php
This makes scopes work again on the Master branch. See issue #148.
The problem was introduced by PR#90.
Because the Token model is casting scopes automatically they do not need encoding in the bridge. Doing so breaks scopes when using an access token created with a scope.
The fix simply sends the array of scopes rather then a json encoded array to the new TokenRepository.
> Fixes scopes error in issue #148

- src/Console/ClientCommand.php
> 'passport:client --password --name=asdf throws RuntimeException

- src/Bridge/UserRepository.php
An issue with the Password Grant is it assumes
that you are using a user model with a hashed password.
This may not be true depending on a number of use cases.
This pull request offers an option similar to what was done with findForPassport earlier in getUserEntityByUserCredentials.
If the code sees a method 'validateForPassportPasswordGrant' in the user class it calls that and lets
the class validate the password sent into the password grant.
First time submitting to a laravel project so if something is wrong in terms of formatting, naming, or something else please let me know so I can fix it.
> Modifying UserRepository so it has another option if the User's class password isn't a standard hashed password.

- src/Passport.php
- src/PassportServiceProvider.php
In reference to https://github.com/laravel/passport/issues/162 and https://github.com/laravel/passport/issues/47
100 years seems to be too long for some environments, maybe 1 year is enough?
> Expire in 1 year by default

- src/Bridge/UserRepository.php
The question came to me when I used Laravel's Passport package to authenticate a different password column on reaching 'oauth/token'
If I want to authenticate from a different 'username' column, it can be done with the following code:
```
public function findForPassport($username) {
return $this->where('id', $username)->first();
}
```
It will take Id, as the 'username' column. What if I want to use a different 'password' column. A column in the table with a different name such as 'uid_token'.
As I went to the `validateForPassportPasswordGrant()` method and called it in my model and expect it to work like the `findForPassport()` it did not work. To see the if condition was causing the problem. But once you write it in this way it worked.
```
if (! $user ) {
return;
} elseif …
```
> fixing the validateForPassportPasswordGrant() method bug

- src/Passport.php
- src/PassportServiceProvider.php
Copy from https://github.com/laravel/passport/pull/63
----
This adds in the implicit grant type.
Same process as the AuthCode grant type except the `response_type` url attribute is set to `token` rather than `code`.
Once a user authorises the request they will be redirected back to the redirect url with the `access_token` directly in the url hash.
Useful for client side JavaScript applications that need to be able to generate an access token but don't have a server side component to retrieve the access token from a code authorization.
This is by default disabled due to many applications possibly not needing or wanting this type of grant. To enable it is as simple as defining a static call in the boot method of `AuthServiceProvider` as you do for pruning of auth tokens:
``` php
/**
* …
```
> Add in implicit grant type

- src/Http/Controllers/AuthorizationController.php
- src/TokenRepository.php
- tests/AuthorizationControllerTest.php
In reference to https://github.com/laravel/passport/issues/16
This PR skips the approval screen if the user has a valid token for the same client that has the same scope as the scope requested, Passport will auto-approve the request and return a new token.
> Bypass auth screen if we already have a token

- src/Bridge/RefreshTokenRepository.php
isRefreshTokenRevoked queries with revoked 1, but 1 does not work with MongoDB and I think should be changed to true.
reference to #204
> Query with revoked true instead of 1 at isRefreshTokenRevoked.

- src/Exceptions/InvalidScopesException.php
- src/Http/Middleware/CheckForAnyScope.php
- src/Http/Middleware/CheckScopes.php
- tests/CheckForAnyScopeTest.php
- tests/CheckScopesTest.php
In reference to #198. This adds the `InvalidScopesException` to allow the user to send a custom response showing which scope(s) have failed authorization. You can catch this exception in your application's exception handler as shown below.
```php
use \Laravel\Passport\Exceptions\InvalidScopesException;
...
/**
* Render an exception into an HTTP response.
*
* @param  \Illuminate\Http\Request $request
* @param  \Exception $exception
*
* @return \Illuminate\Http\Response
*/
public function render($request, Exception $exception)
{
if ($exception instanceof InvalidScopesException) {
return response()->json(['scopes' => $exception->scopes()]);
}
return parent::render($request, $exception);
}
```
> Adds invalid scopes exception

- src/Bridge/ScopeRepository.php
Trying to create a personal token for testing purposes I've found that when I try to create a personal access token with `*` scopes permissions it gets removed from requested scopes.
Digging in the code I've found that only tokens that are granted with `password_grant` can request `*` permission.
This PR attempts to resolve it.
I don't know if its on purpose. If it is, just close this PR.
Cheers.
> Personal access tokens can't get "*" scope

- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
This PR adds an index to the `oauth_access_tokens.client_id` field, since the `Token` model has a `BelongsTo` relationship to the `Client` using this field.
> Add index to oauth_access_tokens.client_id field.

- resources/assets/js/components/AuthorizedClients.vue
Previously if no clients were authorized - even though this is clearly a
valid situation - the user would see a blank screen. To be
consistent with the other sibling Vue components this proposal is to
state that no clients are authorized.
This has the following benefits:
* It's obvious the Vue component is working!
* If someone is using this, authorizes a client, they don't have to
figure out if the Vue component is working OR if they've done
something wrong in their testing or setup.
The test may not be elegant however testing for tokens.length === 0
didn't catch when no clients at all had been authorized. If there is a
more elegant (or more Vue like way), that would be really good.
> State no clients authorized instead of no display.

- src/Passport.php
- src/RouteRegistrar.php
The `/oauth/` prefix is currently hardcoded into each of the route registrar's methods. This PR moves the prefix into the default configuration for the entire passport route group. Now you can easily do:
```php
Passport::routes(null, ['prefix' => 'oauth2/v1']);
```
> Allow for easy configuration of oauth route prefix

- src/TokenRepository.php
Passport check if a token is revoked based on the result of 
`return Token::where('id', $id)->where('revoked', true)->exists();`
It works when the token exists, but when the token does not exists it still returning false.
This problem allows to send an old token and still having access.
**Test Case:**
Create an access_token and copy the value.
Reset the database or just remove that specific access_token from the oauth_access_tokens table
Send a request using the already removed token
You can see that is still passing
It is because `Token::where('id', $id)->where('revoked', true)->exists();` is false when the token does not exists.
> A non existing token should return true for revoked

- src/Passport.php
Usage example:
public function testBasicTest()
{
Passport::actingAs(
factory(User::class)->create(),
['create-servers', 'create-sites']
);
$response = $this->get('/api/manage-servers');
$response->assertStatus(200);
}
> Add actingAs() for use in testing

- src/Http/Controllers/AuthorizationController.php
Small correction to docblocks. Fixed two namespaces, corrected a parameter name in docblock.
> Use correct namespaces in docblocks

- src/ClientRepository.php
The vue client list is sorted in descending order. Makes more sense to sort ascending.
> sort client list ascending

- src/Http/Middleware/CheckClientCredentials.php
- tests/CheckClientCredentialsTest.php
When using the middleware 'client_credentials:some_scope', requests are rejected if the
token was requested using '*' scope during a client credentials grant. They are accepted
if the token was explicitly requested using 'some_scope', in this case.
If I understand correctly that the '*' scope, if granted, would allow all requests for
routes protected by any scope, then this pull request will allow this to happen.
> Accept * scope as valid when verifying client_credentials

- src/Http/Middleware/CheckClientCredentials.php
- tests/CheckClientCredentialsTest.php
A missing scope should lead to an authorization error instead of an authentication one.
> missing scope exception instead of authentication exception

- src/ClientRepository.php
- src/Http/Controllers/AuthorizedAccessTokenController.php
- src/Http/Controllers/ClientController.php
- src/Http/Controllers/PersonalAccessTokenController.php
- src/TokenRepository.php
- tests/AuthorizedAccessTokenControllerTest.php
- tests/ClientControllerTest.php
- tests/PersonalAccessTokenControllerTest.php
Currently it's partially possible to user Passport with other user providers (e.g. Doctrine) as long as they embrace Eloquent being used for storing/retrieving the access tokens.
However to make it fully possible a couple of changes are necessary. 
Other user providers can now with the minimum effort of supplying a `getKey()` on their user model, integrate with Passport. 
No breaking changes should have been made. 
Solves: #326
> Allow Passport to integrate with other user providers

- src/Http/Controllers/DenyAuthorizationController.php
- tests/DenyAuthorizationControllerTest.php
Laravel Passport will redirect incorrectly when the authorization request has been denied by a user while using the implicit flow.
> Fix implicit flow athorization denied redirect

- src/Client.php
When we extending the Client model in our Laravel app and giving different name to it (such as OAuthClient), the relation with no foreign key provided will cause an error: the Laravel thinks that our database field is o_auth_client_id instead of client_id.
This will fix the error.
> Adding foreign keys to Client model relationships

- src/Console/KeysCommand.php
This just guards a developer from running the command and overwriting these files which would then cause issues with decryption
> Adding "force" option so the keys are not overwritten

- src/Console/KeysCommand.php
Wrong indexes for file locations of SSL keys.
> Fix: wrong array index filenames

- src/PassportServiceProvider.php
This will fix https://github.com/laravel/passport/issues/453 that is caused by the changes to thephpleague/oauth2-server from here https://github.com/thephpleague/oauth2-server/pull/776. 
This disables the new permission check that was added in version 6.0.2 of oauth2-server.  I feel like the permission check should be controlled through configuration and not just be statically disabled but passport does not currently have any need for configuration and it would be a pain to add configuration for one setting. So I think some decisions still need to be made on how to handle this change. However, this is a quick solution that restores passport to working order.
> Send CryptKey instance to oauth2 with new permission check disabled.

- src/Http/Controllers/DenyAuthorizationController.php
- tests/DenyAuthorizationControllerTest.php
Fixes an array to string conversion exception when someone denies a request when there are multiple return uris. Fixes https://github.com/laravel/passport/issues/457
Arrays are an allowed return type of `$client->getRedirectUri()`. See:
https://github.com/laravel/passport/blob/3.0/src/Bridge/Client.php#L26
https://github.com/thephpleague/oauth2-server/blob/master/src/Entities/Traits/ClientTrait.php#L40
> Fixing deny response with multiple redirect uris

- src/AuthCode.php
I guess it was a copy-paste from the `Client` model. Since the models aren't tested, this relationship was wrong and no one noticed.
> Fix AuthCode model relationship with Client

- src/Http/Controllers/AccessTokenController.php
- src/Http/Controllers/ApproveAuthorizationController.php
- src/Http/Controllers/AuthorizationController.php
- src/Http/Controllers/ConvertsPsrResponses.php
- src/Http/Controllers/HandlesOAuthErrors.php
- src/Http/Controllers/PersonalAccessTokenController.php
- src/Http/Middleware/CreateFreshApiToken.php
- tests/AccessTokenControllerTest.php
- tests/ApproveAuthorizationControllerTest.php
- tests/AuthorizationControllerTest.php
**Since it's a breaking change, I'm opening it on `master` branch. It would be good to rebase `master` with `3.0` first.**
---
Basically, all responses that were directly returned by `League\OAuth2` classes would fail when used with Laravel middlewares  (`Zend\Diactoros\Response` is incompatible with `Illuminate\Http\Response`). Since passport routes are registered under `web` middlewares, any  middleware applied to `web` that interacts with the response would fail.
This is a simplistic example of a middleware that would fail:
```php
class SecurityHeader
{
public function handle($request, \Closure $next)
{
$response = $next($request);
return $response->header('X-Frame-Options', 'deny');
}
}
```
To avoid monkey patches / `if`s on a bunch of middlewares, my proposal is to use …
> Use Illuminate Response as a standard so that middlewares can always work

- src/Http/Middleware/CreateFreshApiToken.php
Adding back the missing `!` in `responseShouldReceiveFreshToken`.
It was some how left out during df5ddb28318a6ffac2cb0c96fc30e045afa2f9b9 (laravel/passport@df5ddb2#diff-21f5bd46f0aa959bdc94060671ea5b18L92).
Without it a new token will never be set if one has not been set already.
> Fix creating fresh api token

- composer.json
updated firebase/php-jwt dependency which does not have any breaking changes so that it can be useful to use with when the project has 5.0 as dependency for firebase/php-jwt
> updated firebase/php-jwt dependency

- src/Http/Middleware/CreateFreshApiToken.php
For some reasons it was removed 3 weeks ago by @rscafi
https://github.com/laravel/passport/commit/df5ddb28318a6ffac2cb0c96fc30e045afa2f9b9#diff-21f5bd46f0aa959bdc94060671ea5b18L92
Maybe mistake, not sure.
But current dev version doesn't issue tokens at all.
> CreateFreshApiToken doesn't issue a token

- phpunit.xml.dist
- tests/CheckClientCredentialsTest.php
- tests/CreateFreshApiTokenTest.php
- tests/DenyAuthorizationControllerTest.php
- tests/HandlesOAuthErrorsTest.php
- tests/KeysCommandTest.php
- tests/ScopeControllerTest.php
**No source files were touched, only tests were added.**
Now `Controllers` and `Middleware` namespaces both have 100% coverage, especially `CreateFreshApiToken` class, which had a bug introduced by my last PR.
> Bump coverage for Controllers and Middlewares 

- resources/assets/js/components/Clients.vue
- resources/assets/js/components/PersonalAccessTokens.vue
As of Laravel 5.5 errors are wrapped within "errors" field in json response. This causes wrong values being shown in passport components.
> Get proper errors field from JSON response

- src/Console/InstallCommand.php
I fixed a small typo in command option description, this time in the correct branch.
> Fixed small typo in command option description

- src/Http/Middleware/CreateFreshApiToken.php
I added the ability to allow a new token to be given to first party applications from json requests. This way it's possible to implement login functionality without going outside the single page application. The option was there until the commit [2a8198d](https://github.com/laravel/passport/commit/2a8198db7e757ca67ac88e4a8ce6984a2118bc45) that fixed issue [#489](https://github.com/laravel/passport/issues/489). The current commit allows both file downloads and json responses to work properly and close issue [#540](https://github.com/laravel/passport/issues/540)
> A fresh token should also be returned on JsonResponse classes

- src/Bridge/Client.php
The AuthCodeGrant class gets the client identifier of the object obtained from the client repository and compare it with the client_id from request, however the comparison is made using 'not identical'
operator which fails due to the type obtained from the repository (integer) and the type from the request (string).
According to the dock block in League\OAuth2\Server\Entities\Traits\EntityTrait the return type
for the getIdentifier method, must be a string.
> Cast to string the 'identifier' field for Client.

- composer.json
Updated [`mockery/mockery`](https://github.com/mockery/mockery) to [`~1.0`](https://github.com/mockery/mockery/releases/tag/1.0).
> [4.0] Updated mockery in composer.json

- .travis.yml
- composer.json
- phpunit.xml.dist
- tests/AccessTokenControllerTest.php
- tests/ApiTokenCookieFactoryTest.php
- tests/ApproveAuthorizationControllerTest.php
- tests/AuthorizationControllerTest.php
- tests/AuthorizedAccessTokenControllerTest.php
- tests/BridgeAccessTokenRepositoryTest.php
- tests/BridgeClientRepositoryTest.php
- tests/BridgeScopeRepositoryTest.php
- tests/CheckClientCredentialsTest.php
- tests/CheckForAnyScopeTest.php
- tests/CheckScopesTest.php
- tests/ClientControllerTest.php
- tests/DenyAuthorizationControllerTest.php
- tests/HasApiTokensTest.php
- tests/KeysCommandTest.php
- tests/PassportTest.php
- tests/PersonalAccessTokenControllerTest.php
- tests/PersonalAccessTokenFactoryTest.php
- tests/ScopeTest.php
- tests/TokenGuardTest.php
- tests/TokenTest.php
- tests/TransientTokenControllerTest.php
- tests/TransientTokenTest.php
Updated `phpunit/phpunit` to `~6.0`.
Dropped support to `PHP 5.6`, as PHPUnit 6.0 [requires PHP 7.0](https://github.com/sebastianbergmann/phpunit/blob/master/composer.json#L25)?
PS: I've used [this commit](https://github.com/laravel/framework/pull/17864) from `laravel/framework` to prevent failed tests.
> [5.0] Update to PHPUnit 6

- src/Bridge/AccessTokenRepository.php
- src/Http/Middleware/CheckClientCredentials.php
- tests/CreateFreshApiTokenTest.php
There are two class properties and one test function that are marked as `private`. This PR changes their visibility to `protected`.
While this doesn't matter much for the test function, the private property requires the developer to redefine the property when extending the affected classes (which is how I came across the issue).
> Changed private properties and functions to protected.

- src/Http/Controllers/DenyAuthorizationController.php
- tests/DenyAuthorizationControllerTest.php
Redirect denied authorization callbacks to the redirect_uri in the authorization request if it is one of the redirect_uris configured for the client; otherwise, use the first redirect_uri configured for the client.
Fixes issue #621
> Redirect denied authorization callbacks to the correct redirect_uri

- src/ClientRepository.php
- src/Console/ClientCommand.php
This fix moves the `PersonalAccessClient` model instantiation from the artisan command to the ClientRepository. 
It allows to easily swap Passport's persistence layer by binding a custom repository inside the container.
> Move Model instantiation to repository

- src/Guards/TokenGuard.php
- tests/TokenGuardTest.php
This is an alternative fix for Issue #632. (PR #634)
The proposal here is to reset the `Authorization` header on the request if OAuth2 fails, avoiding that the `user()` method try again to authenticate causing the infinite recursion.
Note that I've updated the tests too.
> Alternative fix to Issue #632

- composer.json
- config/passport.php
- src/Bridge/ClientRepository.php
- src/PassportServiceProvider.php
- tests/PassportServiceProviderTest.php
Currently the only way to set encryption keys in Passport is with local files (`/storage/oauth-private.key` and `/storage/oauth-public.key`). However, this can be problematic in multi-server setups, where the same keys must be shared across multiple systems. In those situations, it's better to use environment variables. This PR adds the ability to do that.
The PHP League's OAuth 2.0 Server library supports passing either a file path or text version of the key to their `CryptKey` class. It does this by doing a regular expression to check if the string provided matches a RSA key pattern. If yes, it automatically saves the key to a temporary file, otherwise it treats the string as a file path. Unfortunately there was a bug with this regular expression in version 6 of the League's library, …
> Add ability to set encryption keys from config

- composer.json
This is currently wrong as `illuminate/contracts` v5.6 requires at least php7.1.
> Bump up minimum php version required

- src/AuthCode.php
- src/Client.php
- src/ClientRepository.php
- src/HasApiTokens.php
- src/Passport.php
- src/PersonalAccessClient.php
- src/Token.php
- src/TokenRepository.php
With this PR, one can change and extend any model classes provided by Passport in a similar fashion as Spark. If people need stuff like UUIDs (#122), they can just add this functionality themselves without touching the Passport codebase.
> Make model classes configurable

- src/Passport.php
- tests/PassportTest.php
Sorry, this is a fix for the invalid $client property name 😓
> Fixed invalid static property $client

- src/Bridge/ClientRepository.php
- tests/ClientRepositoryTest.php
As in https://tools.ietf.org/html/rfc6749#section-4.4:
> The client credentials grant type MUST only be used by confidential clients.
This adds a check that the given client is confidential (has a secret), which allows public clients to be created without the risk that they will be used to obtain a client_credentials grant.
Also adds tests for the changed function.
> Protect client credentials grant

- src/Client.php
Following on from https://github.com/laravel/passport/pull/729#issuecomment-394377462, this change casts `grant_types` to an array in the Client Eloquent model.
> feat: add array cast for grant_types

- src/HasApiTokens.php
The `HasApiTokens` trait defines a `HasMany` relationship - `tokens()` - but the docblock has its return type set to `Collection` instead of `HasMany`, this PR fixes that.
**Changes:**
```diff
src/HasApiTokens.php
/**
* Get all of the access tokens for the user.
*
-     * @return \Illuminate\Database\Eloquent\Collection
+     * @return \Illuminate\Database\Eloquent\Relations\HasMany
*/
public function tokens() { [...] }
```
> Correct return type of tokens relation.

- src/ClientRepository.php
This builds on the work done in https://github.com/laravel/passport/commit/47eaf7221411ba337faa518e20fdfaf9d9548cbf to remove the hard coding of the `id` field in favour of using [Model::getKeyName](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Model.php#L1214)
Third part packages exist which allow Laravel and Laravel Passport to be used with MongoDB. This works in Passport 4.0. However, https://github.com/laravel/passport/commit/47eaf7221411ba337faa518e20fdfaf9d9548cbf prevents Passport from being used with MongoDB because the primary key field is `_id`
> Remove hard-coded model key name in favour of Model::getKeyName()

- src/Http/Controllers/DenyAuthorizationController.php
- tests/DenyAuthorizationControllerTest.php
**Problem**
Currently the `deny` function of `src/Http/Controllers/DenyAuthorizationController.php` always simply appends a separator of either a `#` or `?` based on the outcome `$authRequest->getGrantTypeId()`, see: https://github.com/laravel/passport/blob/6.0/src/Http/Controllers/DenyAuthorizationController.php#L47
This works fine when using a redirect URL for a OAuth Client without a existing query string, such as:
`https://example.com/some_callback_function`
However, when providing a redirect URL for a OAuth Client that already contains a query string, such as:
`https://example.com/index.php?action=some_callback_function`
You will be redirected to:
`https://example.com/index.php?action=some_callback_function?error=access_denied&state=`
Which contains `?` twice, resulting in a …
> Allow for URI with already existing query string

- src/Console/ClientCommand.php
This PR expands the existing `passport:client` artisan command to allow developers to use it to create `client_credentials` grant clients.
This currently isn't possible at all with the `passport:client` command since the other client options either set the `personal_access_client` or `password_client` fields to `true`, or require a user ID for to be entered.
> Added support for creating client credentials grant clients via artisan command

- src/Console/KeysCommand.php
`passport:install` is failing with:
`openssl_pkey_new(): private key length is too short; it needs to be at least 384 bits, not 0`
Type casting the `passport:key` `--length` argument to an integer fixes this issue.
The RSA::createKey method requires an integer to be passed.
https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA.php#L334
> Fix key length issue on passport:install

- src/Http/Controllers/AuthorizationController.php
This small PR will make the parseScopes method returns an array of unique scopes.
> Unique scopes on AuthorizationController

- src/Guards/TokenGuard.php
- src/Passport.php
This PR adds the new option `Passport::dontUnserializeCookies();` that you can place it in `AuthServiceProvider` to instruct passport that tokens shouldn't be unserialized.
> Adapt for laravel breaking change

- src/AuthCode.php
- src/Bridge/AuthCodeRepository.php
There's a `Authcode` Model for the `oauth_auth_codes` table, but not used yet. 
Just like the [TokenRepository.php](https://github.com/laravel/passport/blob/7.0/src/TokenRepository.php#L18) does so, `Authcode` should be used to persisting new authcode.
Also, this can solve the problem that the table name `oauth_auth_codes` is hardcoded in `AuthCodeRepository.php`.
> `Authcode` model should be used for persisting new authcode

- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- tests/CheckClientCredentialsForAnyScopeTest.php
The current implementation has the middlewares [CheckScopes](https://github.com/laravel/passport/blob/7.0/src/Http/Middleware/CheckScopes.php) and [CheckForAnyScope](https://github.com/laravel/passport/blob/7.0/src/Http/Middleware/CheckForAnyScope.php) what gives us flexibility to check if the current request has all or one of the desired scopes.
This PR adds a new middleware that brings similar flexibility when dealing with client credentials grant type.
> [7.0] Add middleware CheckClientCredentialsForAnyScope

- src/Passport.php
- src/PassportServiceProvider.php
According to the RFC if a client omits a scope, the server can choose to use a default scope. League OAuth2 server supports setting a default scope, but Laravel does not.  This PR adds support for setting a default scope in Laravel. (see discussion on https://github.com/laravel/passport/issues/870). 
The scope can be passed as either an array or a space delimited list, and can be set in AuthServiceProvider
```
Passport::setDefaultScope('email username');
```
This PR should be fully backwards compatible with 7.0. If the user doesn't add a default scope, nothing changes.
> [7.0] Support a default scope when no scope was requested by the client

- database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
- database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
This is because the client id autoincrements. We don't add foreign key indexes ourselves but if you try to add them afterwards you'll have to first change the column type of the client_id columns because otherwise they don't match the increments column. We can immediately use the proper type in the migrations here.
Sending this to the 8.0 branch because I wasn't too sure if this would be breaking or not so better play it safe.
Fixes https://github.com/laravel/passport/issues/912
> [8.0] Use unsignedInteger column type for client_id columns

- src/Console/ClientCommand.php
When using `passport:client` commands, add `redirect_uri` and `user_id` options. Useful for automated builds.
> [7.0] Added redirect_uri and user_id options to cli

- src/Console/ClientCommand.php
The command ask a required question  but allows user to skip; which cause failure in mysql insert query.
Just press enter when the command asks
"What should we name the client?:"
```
php artisan passport:client --client
```
This PR will auto guess the name when no name is specified or input by user.
> [7.0] Make name an optional question

- src/Bridge/RefreshTokenRepository.php
- tests/BridgeRefreshTokenRepositoryTest.php
When a check if performed to determine if a refresh token is revoked or not, it's unnecessary to also check if its corresponding access token is revoked. It's perfectly possible to issue a new access token if the old access token is either revoked or pruned as long as the refresh token is valid.
Fixes https://github.com/laravel/passport/issues/917
> [7.0] Fix revoked refresh token check

- src/AuthCode.php
This follows the same rule as the Token model. Both don't have auto incrementing IDs so we should set this to false.
Fixes https://github.com/laravel/passport/issues/895
> [7.0] Do not auto increment AuthCode ID

- src/Http/Controllers/ClientController.php
- src/Http/Rules/RedirectRule.php
- tests/ClientControllerTest.php
- tests/RedirectRuleTest.php
This change allows for multiple redirects in a comma separated list when adding them through the ClientController. It makes use of a custom validation rule which will separate the urls by the comma and run the url validator rule over each one individually.
Except for `https://example.com` individually, the value of `https://example.com,https://example2.com` would be allowed as well.
I took the approach of a custom validation rule because it seemed the most flexible in terms of implementing the custom logic. It allows for re-using Laravel's url validation rule.
Fixes https://github.com/laravel/passport/issues/897
> [7.0] Allow multiple redirects when creating clients

- src/Http/Controllers/AuthorizedAccessTokenController.php
- src/Http/Controllers/ClientController.php
- src/Http/Controllers/PersonalAccessTokenController.php
- tests/AuthorizedAccessTokenControllerTest.php
- tests/ClientControllerTest.php
- tests/PersonalAccessTokenControllerTest.php
This adds proper responses and HTTP statuses for the destroy methods on success.
Fixes https://github.com/laravel/passport/issues/687
> [7.0] Add responses for destroy methods

- composer.json
> [7.0] Add ext-json dependency

- resources/views/authorize.blade.php
If we use second parameter for register routes default views are broken
Passport::routes(false, ["prefix" => "something"]);
> [7.0] Changed the way to get action path from url() to route()

- src/Bridge/ScopeRepository.php
- tests/BridgeScopeRepositoryTest.php
As mentioned in https://github.com/laravel/passport/issues/516, using the `*` character to request all scopes for the Client Credentials grant type is valid.
This PR will allow the character to be used when requesting an access token with the Client Credentials Grant.
> [7.0] Allow '*' scope to be used with Client Credentials

- src/Bridge/RefreshTokenRepository.php
`fire()` was deprecated and `dispatch()` should be used. Also `\Illuminate\Contracts\Events\Dispatcher` has `dispatch()` but not `fire()`
> Replace fire() with dispatch()

- src/Bridge/RefreshTokenRepository.php
- src/Passport.php
- src/RefreshToken.php
- src/RefreshTokenRepository.php
- tests/BridgeRefreshTokenRepositoryTest.php
- tests/PassportTest.php
This is a resend for https://github.com/laravel/passport/pull/946
@donovanhare was already so kind to add additional tests.
The main purpose of this PR is to provide a way to customize the refresh tokens table which is currently hardcoded. This PR converts the functionality in the same way as done for all the other tables and thus brings along more consistency across the codebase.
Fixes https://github.com/laravel/passport/issues/864
> [8.0] Customize RefreshToken

- src/Passport.php
Resubmitting with explanation as requested by @driesvints in #975 
The core framework fixed this same bug with the core actingAs method but
it seems it was missed for Passport! Check this PR for more details:
https://github.com/laravel/framework/pull/25873
I don't think we need the conditional, and certainly not the truthy check of it on the right side. Setting something to false that's already false won't have any negative effects. The `User` that's passed to the auth guard is expecting an `Authenticatable` which also extends `Model`, which should always have `wasRecentlyCreated`.
I look at this as "Hey look we need this to be false, why do we care if it's true first?"
> [7.0] Change wasRecentlyCreated to false

- .travis.yml
This PR removes the nightly builds as they don't provide too much value at this point. I've also not seen too much other OS projects that do this on a dependency level (besides the nightly language builds themselves which we could do or not).
Also tweaked the script so it's not much more clear and concise. If this is accepted then I'll start adding these changes to all the other libraries as well.
> [7.0] Tweak Travis setup

- src/Guards/TokenGuard.php
Just changes the comment from saying the request **is** from a valid source when the CSRF token doesn't match to saying that it **is not** from a valid source.
> [7.0] Fix incorrect comment in TokenGuard::getTokenViaCookie

- tests/AccessTokenControllerTest.php
- tests/AuthorizationControllerTest.php
- tests/HandlesOAuthErrorsTest.php
- tests/HasApiTokensTest.php
- tests/TokenGuardTest.php
These tests were only passing if you ran the entire test suite.  If you ran an individual test it would fail with this message:
```
./vendor/bin/phpunit ./tests/AuthorizationControllerTest.php
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
.E.                                                                 3 / 3 (100%)
Time: 118 ms, Memory: 10.00 MB
There was 1 error:
1) Laravel\Passport\Tests\AuthorizationControllerTest::test_authorization_exceptions_are_handled
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Config\Repository] is not instantiable.
/Users/matt/code/laravel/passport/vendor/illuminate/container/Container.php:962
/Users/matt/code/laravel/passport/vendor/illuminate/container/Container.php:800 …
```
> [7.0] Clear the container between tests & bind necessary mocks

- src/Client.php
- src/Http/Controllers/AuthorizationController.php
- tests/AuthorizationControllerTest.php
This PR adds a new method `Client::skipsAuthorization()`. If the method returns true the client is allowed to skip the authorization prompt.
It's considered best practice to use the Authorization code grant for first party mobile apps and SPAs but Passport currently requires you to show an authorization prompt to the user ("{client} is requesting permission...") with this grant type.
It doesn't really make sense to show the authorization prompt for first party clients.  If Google asked you to grant permission to Google every time you logged in to gmail it would be pretty confusing.
Allowing first party clients to skip the authorization prompt is supported by the majority of OAuth servers: Auth0, Otka, Doorkeeper, Django OAuth Toolkit, IdentityServer, Keycloak, Ory Hydra, and others.  It's …
> [7.0] Allow first party clients to skip the authorization prompt

- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
I change declaration $server property in CheckClientCredentialForAnyScope from __private__ to __protected__, this is useful if anyone wants to extends this middleware.
> [7.0] Change server Property type in CheckClientCredentialForAnyScope

- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- tests/CheckClientCredentialsForAnyScopeTest.php
- tests/CheckClientCredentialsTest.php
I made a pull request for issue [#691](https://github.com/laravel/passport/issues/691).
So when someone passes a token in their request which belongs to first party clients (such as `Password Credentials`), our middlewares will throw an `Illuminate\Auth\AuthenticationException` Exception.
So only those who have issued access token with `Client Credentials` grant type can go through `CheckClientCredential` & `CheckClientCredentialForAnyScope` Middlewares.
> Fix exception will thrown if token belongs to first party clients

- src/Bridge/AuthCodeRepository.php
Current implementation does not respect `$connection` property in custom AuthCode model and always use Laravel's default connection.
> [8.0] Fix auth codes table customization

- src/PassportServiceProvider.php
The PassportServiceProvider is lacking a `mergeConfigFrom` call, which breaks the key check in `makeCryptKey` unless one first copies the default `config/passport.php` into their app's config directory.  Copying the config should only be required when one wants to override the default values.  I ran into this issue when trying to set my keys [using environment variables](https://laravel.com/docs/5.8/passport#deploying-passport) in a new project.
> [7.0] Merge default Passport configuration

- src/Console/KeysCommand.php
Benefit: This can significantly speed up tests that call `artisan passport:install` by avoiding work whose results will be discarded anyway (see https://stackoverflow.com/a/50243105/153354 for an example where this is recommended).
No changes in observable behavior, we only avoid unnecessary work.
I guess this should also be forward-ported to 8.0 once merged, or will 7.0 automatically be merged into 8.0?
> [7.0] Make passport:keys only generate keys when needed.

- tests/AccessTokenControllerTest.php
- tests/AuthorizationControllerTest.php
The tests [are failing on master](https://travis-ci.org/laravel/passport/jobs/568492696).
A test that was removed in #937 was merged back in accidentally and a use statement is missing in another test.
> Resolve test failures

- src/Passport.php
- src/Token.php
- tests/TokenTest.php
This PR introduces the concept of inherited scopes.
By setting `Passport::$withInheritedScopes = true;` in your `AppServiceProvider.php` file you can enable this new feature (which is disabled by default).
Once enabled it allows the access to be granted or not depending on the presence of parent scopes.
This is a common pattern which is used by [Github](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes) for their API scopes - but not only.
A user will have the possibility to *also* execute an action requiring the `admin:webhooks:create` scope, if he already has already been granted the following scopes `admin:webhooks`, `admin`.
---
Note:
If merged, additional documentation should be added to https://laravel.com/docs/5.8/passport.
> [7.0] Let Passport support inherited parent scopes.

- database/migrations/2019_07_17_000001_make_client_secret_nullable.php
- resources/js/components/Clients.vue
- src/Bridge/ClientRepository.php
- src/Client.php
- src/ClientRepository.php
- src/Http/Controllers/ClientController.php
- tests/AccessTokenControllerTest.php
- tests/AuthorizationControllerTest.php
- tests/BridgeClientRepositoryTest.php
- tests/ClientControllerTest.php
This pull request adds support for public clients.
The league/oauth2-server now supports using both public and confidential clients with the authorization code grant. The recommended flow for single page applications and native apps is the auth code grant with a public client and PKCE. Supporting public clients makes it possible for developers to use the authorization code grant with PKCE instead of the insecure implicit grant.
Previously all clients were required to have a secret. If you used the implicit grant the secret just wasn't checked. We can't just skip checking the secret for the auth code grant like we were doing with the implicit grant because we need to check the secret if it was issued.
Instead we need to offer the ability to create public clients, and only check the …
> [8.0] Allow public clients

- composer.json
- src/Guards/TokenGuard.php
- tests/TokenGuardTest.php
This updates `TokenGuard` to accept requests with a valid encrypted `X-XSRF-TOKEN` HTTP header in the same way as Laravel's [`VerifyCsrfToken` middleware](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php#L152).
Amongst other things, this would allow us to simplify Laravel's `bootstrap.js` by taking advantage of Axios's default functionality to automatically send the `X-XSRF-TOKEN` header on same-origin requests using the contents of the `XSRF-TOKEN` cookie.
I note that this feature has been requested and rejected several times, often because of concerns it opens a CSRF vulnerability. I believe this is not the case because we are only opening it to accept requests with a valid `X-XSRF-TOKEN` *HTTP header*, which will never be …
> [7.0] Accept requests with the encrypted X-XSRF-TOKEN HTTP header

- src/Token.php
This was made to fix usage of Token model in relations after upgrade to laravel 6.0.
Made this according to https://laravel.com/docs/6.0/upgrade#eloquent-primary-key-type
> added $keyType = 'string' to Token model

- src/Passport.php
Laravel Passport already provides an `actingAs` method that mocks the user authentication. This pull request adds the method `actingAsClient` to mock the client authentication (optionally using certain scopes).
```php
Passport::actingAsClient($client);
Passport::actingAsClient($client, ['check-status', 'place-orders']);
```
If you currently want to test an API route that uses client authentication, you have to make an actual request to the `/oauth/token` route to get a client access token. Then you have to add that token to the `Authorization` header of the next request that tests the API route.
_Fixes issues [#514](https://github.com/laravel/passport/issues/514) and [#680](https://github.com/laravel/passport/issues/680)._
This method was already proposed in an older pull request …
> [7.x] 'actingAsClient' method for tests

- src/Bridge/Client.php
Fixes https://github.com/laravel/passport/issues/1089.
Will benefit anyone who wishes to switch to native prepared statements for performance or other reasons.
Since it should be 100% backwards compatible, please let me know what kinds of tests would one need for such cases.
> [7.x] Cast returned client identifier value to string

- .styleci.yml
Alpha ordered imports will become the default for the laravel preset in a few minutes time on styleci.io.
> [7.0] Update .styleci.yml

- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- tests/CheckClientCredentialsForAnyScopeTest.php
- tests/CheckClientCredentialsTest.php
The 'check client credentials' middleware currently fetches the client via the token. That means it first has to get the token and then load the client relation. The client id is already present in psr request via 'oauth_client_id' attribute. By using that attribute, the middleware has to make one less database query.
It also doesn't need to fetch the token in order to check the scopes. The psr request includes the scopes via 'oauth_scopes' attribute.
These psr attributes were used by the middleware in the previous version(s) of Passport.
> [9.x] Use psr request attributes in 'check client credentials' middleware

- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- tests/CheckClientCredentialsForAnyScopeTest.php
- tests/CheckClientCredentialsTest.php
Reverting this for now since it is a slight change in behavior that I don't think is warranted.
> Revert "[9.x] Use psr request attributes in 'check client credentials' middleware"

- src/Passport.php
The `Passport::actingAsClient()` is broken since version 8.0, because of the changes made by #1040. I updated the method to also mock the use of `TokenRepository` property.
> [8.x] Fix 'actingAsClient' testing method

- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- src/Http/Middleware/CheckCredentials.php
custom implementation of middleware if needed.
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> [8.x] Add abstract CheckCredentials middleware and allows to create

- UPGRADE.md
There is no migration included in 8.0 which updates the 'oauth clients' table, so this should not be mentioned in the upgrade guide
> [8.x] Update 'upgrade to 8.0' guide to remove mention of included upgrade migration

- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- tests/CheckClientCredentialsForAnyScopeTest.php
- tests/CheckClientCredentialsTest.php
This commit "revert" Passport to its regular behavior where the client.credentials middleware only determines if the received access token is valid, which is only possible when the client credentials are correct, independently of the type of the client or even the type of the access token itself.
This was already discussed on this issue (#1125).
> [9.x] Client credentials middleware should allow any valid client (#1125)

- src/Http/Controllers/AuthorizationController.php
- src/Http/Controllers/AuthorizedAccessTokenController.php
- src/Http/Controllers/ClientController.php
- src/Http/Controllers/PersonalAccessTokenController.php
- src/Http/Controllers/RetrievesAuthRequestFromSession.php
- src/Http/Controllers/TransientTokenController.php
- src/Http/Middleware/CreateFreshApiToken.php
- src/TokenRepository.php
- tests/ApproveAuthorizationControllerTest.php
- tests/AuthorizationControllerTest.php
- tests/AuthorizedAccessTokenControllerTest.php
- tests/ClientControllerTest.php
- tests/CreateFreshApiTokenTest.php
- tests/DenyAuthorizationControllerTest.php
- tests/PersonalAccessTokenControllerTest.php
- tests/TransientTokenControllerTest.php
Switch from getKey to getAuthIdentifier to better match the core and work better with other 3rd party packages. This pull request closes #1006
> [9.x] Switch from getKey() to getAuthIdentifier() to match Laravel core

- tests/CheckClientCredentialsForAnyScopeTest.php
- tests/CheckClientCredentialsTest.php
- tests/CheckForAnyScopeTest.php
- tests/CheckScopesTest.php
- tests/DenyAuthorizationControllerTest.php
- tests/PassportTest.php
> The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageRegExp() instead.
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Use avoid using deprecated PHPUnit annotation.

- src/Exceptions/OAuthServerException.php
This would allow custom exception handler such as `dingo/api` to retrieved proper HTTP status code when rendering exception.
```php
use Laravel\Passport\Exceptions\OAuthServerException;
// ...
tap($this->app->make('api.exception'), static function ($handler) {
$handler->register(static function (OAuthServerException $e) {
return abort($e->getStatusCode(), $e->getMessage());
});
});
```
Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>
> Allow access to HTTP response status code on OAuthServerException.

- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- src/Bridge/ClientRepository.php
- src/Client.php
- src/Passport.php
- tests/BridgeClientRepositoryHashedSecretsTest.php
- tests/BridgeClientRepositoryTest.php
A part of the discussion in #14 was about having client credentials secrets securely stored in the database. While encrypting this value when storing and decrypting when retrieving would be ok to do, it doesn't provide any real value as it can be easily decrypted if the attacker already has access to the application.
Another, more viable option was to treat the secret like a user password and hash it. It's not necessary to know the actual value when authenticating, so it doesn't need to be stored in plaintext or have the ability to be decrypted. This increases the security of the API by removing the ability for attackers, abusive users, or other parties to get a hold of those secrets (that sometimes give access to critical API endpoints).
This PR introduces a lightweight, optional way of …
> Allow client credentials secret to be hashed

- src/Bridge/UserRepository.php
```php
/**
* Find the user instance for the given username and validate its password.
*
* @param string $username
* @param string $password
*
* @return null|\App\User
*/
public function findAndValidateForPassport($username, $password)
{
$user = $this->where('username', $username)->first();
if (! $user) {
return;
}
return Hash::check($password, $user->password);
}
```
This PR updates the UserRepository to check if the `findAndValidateForPassport` method exists on the `User` model. It allows you to combine the existing `findForPassport` and `validateForPassportPasswordGrant` methods.
Why would you want to use this `findAndValidateForPassport` method on your `User` model?
Passport assumes the user with the username always already exists and always uses a traditional password to authenticate. …
> [8.x] Modify UserRepository to check for 'findAndValidateForPassport' method

- src/Console/ClientCommand.php
Now you can create a public Auth Code Grant Type Client (for PKCE) with `php artisan passport:client --public`. Omitting `--public` will simply generate a confidential Client with a secret.
> [8.x] Update ClientCommand to support public clients

- src/Bridge/UserRepository.php
Currently there is no way to specify the hasher implementation because the hash manager would always return the default driver implementation. There is also no reason for the entire hash manager being there as we only need the hasher implementation and `$hasher->driver()` which was called in the constructor always returns the default one which is gonna be [injected by default anyway](https://github.com/laravel/framework/blob/v6.9.0/src/Illuminate/Hashing/HashServiceProvider.php#L22).
There are no breaking changes here as [the HashManager also implements the hasher interface](https://github.com/laravel/framework/blob/v6.9.0/src/Illuminate/Hashing/HashManager.php#L8).
I'm sending this to the `master` branch as per @taylorotwell comment in https://github.com/laravel/passport/pull/1154
> [9.x] Use Hasher interface instead of HashManager

- composer.json
- src/Passport.php
- tests/Feature/ActingAsClientTest.php
- tests/Feature/ActingAsTest.php
- tests/Feature/PassportTestCase.php
- tests/KeysCommandTest.php
- tests/bootstrap.php
Currently Passport is being only unit tested which is great except that each method where Laravel global helpers are being used cannot be tested at all.
This is the case with the `Passport::actingAsClient` method which uses the `app` helper to resolve and bind stuff with the container. Because of that the method wasn't tested which resulted in it being broken from July (https://github.com/laravel/passport/pull/1040) till November (https://github.com/laravel/passport/pull/1119). The fix was made in November but as there are still no tests for it we won't know if it breaks again in the future.
This PR adds Orchestra Testbench so that we can write full functional tests with the whole framework and I've added tests for the `Passport::actingAs` and `Passport::actingAsClient` methods.
In doing …
> [8.x] Add tests for Passport::actingAs and Passport::actingAsClient

- src/Console/PurgeCommand.php
- src/PassportServiceProvider.php
This adds an artisan command, which allows for users to purge revoked and/or expired tokens and auth codes.
With a single command to purge revoked and/or expired tokens, users can quickly schedule this to happen on a regular basis or easily purge them once in a while manually. 
One command is added with two options:
```
php artisan passport:purge` # This will purge both revoked and expired tokens and auth codes
php artisan passport:purge --revoked` # This will only purge revoked tokens and auth codes
php artisan passport:purge --expired` # This will only purge expired tokens and auth codes
php artisan passport:purge --revoked --expired` # This will purge both expired tokens and auth codes
```
> Feature: Purge Command for revoked and/or expired tokens and auth codes

- database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
- database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php
- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
I was looking through the migrations and saw that some of them seem pretty dated and don't use bigIncrements and indexes on certain possible relationships like the `user_id` field [here][1].
[1]: https://github.com/KieronWiltshire/passport/blob/8.x/database/migrations/2016_06_01_000004_create_oauth_clients_table.php#L18
> [8.x] Shouldn't the migrations use bigIncrements and indexes on relationships?

- database/factories/PassportClientFactory.php
- src/PassportServiceProvider.php
In the help documentation for 6.x and up there is reference in the testing section to test Client access with the method `Passport::actingAsClient` and that it takes a Client model created by a factory to be passed in. https://laravel.com/docs/6.x/passport#testing
```php
use Laravel\Passport\Client;
use Laravel\Passport\Passport;
public function testGetOrders()
{
Passport::actingAsClient(
factory(Client::class)->create(),
['check-status']
);
$response = $this->get('/api/orders');
$response->assertStatus(200);
}
```
Just trying that code out of the box fails since there is no published asset for a `Laravel\Passport\Client` factory. The user is left to make one on their own.
This will publish a Client factory that the user can use for this.
I don't believe it will break any existing …
> [8.x] Add a Passport Client factory to Passport publishing

- .travis.yml
- database/factories/PassportClientFactory.php
- phpunit.xml.dist
- tests/Feature/AccessTokenControllerTest.php
- tests/Feature/PassportTestCase.php
After adding the support for feature tests in #1155 I'm sending this PR which contains feature tests for getting the access token with the password grant.
If this gets merged I'll probably also add the tests for the other grants when I'll have the time.
> [8.x] Add tests for getting the access token with the password grant

- resources/views/authorize.blade.php
- src/Exceptions/InvalidAuthTokenException.php
- src/Http/Controllers/ApproveAuthorizationController.php
- src/Http/Controllers/AuthorizationController.php
- src/Http/Controllers/DenyAuthorizationController.php
- src/Http/Controllers/RetrievesAuthRequestFromSession.php
- tests/ApproveAuthorizationControllerTest.php
- tests/AuthorizationControllerTest.php
- tests/DenyAuthorizationControllerTest.php
This implements a new authToken which will be set in the authorization form to verify that the authorization request isn't re-triggered.
> [8.x] Implement auth token for access requests

- src/Http/Controllers/RetrievesAuthRequestFromSession.php
When the auth token doesn't matches it's best to clear the session keys so they can't be tampered with any further.
> [8.x] Forget session keys on invalid match

- src/PassportServiceProvider.php
https://github.com/illuminate/support/blob/6.x/ServiceProvider.php#L60-L67
This solved issue with laravel/lumen-framework#938
> [8.x] mergeConfigFrom() already check if app is running with config cached.

- src/Token.php
- tests/TokenTest.php
Previously the first element returns by `resolveInheritedScopes` was an empty string.
This PR fixes this.
> [8.x] Fix resolveInheritedScopes.

- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
**Description:**
Passport returns _500 Internal Server Error_ response on validating recently deleted client.
**Steps To Reproduce:**
1. Issue client credentials grant token
2. Request a token using _oauth/token_ endpoint
3. Delete client from _oauth_clients_ table
4. Send request to any valid api endpoint using Bearer authorization and token from step 2
5. Passport returns _500 (Internal Server Error)_ response instead of _401 (Unauthorized)_ response
> Fix 500 Internal Server Error response on validating recently deleted client

- .github/workflows/tests.yml
- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- src/Bridge/Client.php
- src/Bridge/ClientRepository.php
- src/Bridge/UserRepository.php
- src/Client.php
- src/ClientRepository.php
- src/Console/ClientCommand.php
- src/Console/InstallCommand.php
- src/Guards/TokenGuard.php
- src/Http/Middleware/CheckCredentials.php
- src/PassportServiceProvider.php
- src/PassportUserProvider.php
- tests/BridgeClientRepositoryTest.php
- tests/TokenGuardTest.php
This PR adds support to allow passport to use and enforce multiple providers.
Currently, Passport only uses the `UserProvider` passed into it from the `RequestGuard`. This can be problematic if you have more than one provider (config/auth.php) that needs to be authenticated. Since Passport has no knowledge of other `UserProvider` you can end up in situations where the wrong user is authenticated and returned.
This PR adds support to optionally set the provider that should be used on the `Passport\Client`. If a provider is defined on the `Passport\Client`, it will compare it against the `UserProvider` coming in from the `RequestGuard` and return the user if they match. This ensures that the user being returned is coming from the right model. If there is a mismatch, no user is returned, …
> [9.x] Initial support for multiple providers

- config/passport.php
- src/Client.php
- src/Console/InstallCommand.php
- src/Passport.php
- src/PassportServiceProvider.php
This PR adds a new `--uuids` flag that can be used when calling `passport:install`. This flag will automatically configure Passport for using UUIDs for client IDs instead of auto-incrementing IDs. This should not be a breaking change.
> [8.x] Automatic configuration of client uuids

- composer.json
These old versions aren't needed anymore and the newer v5 has been around for 3 years already.
> [9.x] Drop support for old JWT versions

- src/Console/ClientCommand.php
- src/Console/HashCommand.php
- src/PassportServiceProvider.php
This is a PoC for a `passport:hash` command to help ease the migration to hashed client secrets. Follow-up for https://github.com/laravel/passport/pull/1145
I've added a confirmation to the command to be safe. And I've added a check to validate if the password is already hashed.
This PR also fixes a small regression where the plainSecret wasn't shown after creating a client with the `passport:install` command.
> [9.x] Implement passport:hash command

- UPGRADE.md
Depends on https://github.com/laravel/passport/pull/1238
> [9.x] Update UPGRADE.md

- resources/js/components/Clients.vue
- src/Http/Controllers/ClientController.php
Fixes displaying the secret one-time upon creation.
> [9.x] Fix displaying secret in Vue component

- src/Guards/TokenGuard.php
This fixes #1243. 
The provider should only be verified when it has a known client, which only happens with a bearer token.
> Moved provider check to bearer token only

- src/Console/HashCommand.php
This adds the force option (--force) to the passport:hash command. In environments such as Vapor where users are unable to interact with the terminal, this gives the ability to override the verification prompt and force the command to run.
Closes #1250
> [9.x] Add force option to hash command

- UPGRADE.md
- config/passport.php
- src/Passport.php
- src/PersonalAccessTokenFactory.php
This is an alternative to https://github.com/laravel/passport/pull/1256 which implements secret hashing in a proper way for personal access clients. This will require some additional upgrade steps for the users unfortunately but at least this allows proper hashing for all client types. _People who have already hashed their personal access client secrets will need to create new personal access clients with new secrets._
Ideally in a follow-up pr for this, we'll get rid of the required `Passport::personalAccessClientId` and `Passport::personalAccessClientSecret` calls so the developer doesn't needs to implement these anymore. But that'll have to be for a next major version release.
Fixes #1252
> [9.x] Implement personal access client config

- src/Console/ClientCommand.php
It seemed better to explicitly warn about the one-time-secret like in the modal pr I just sent in.
> [9.x] Warn about one-time-hashed-secret

- UPGRADE.md
- resources/js/components/Clients.vue
- src/Http/Controllers/ClientController.php
This PR implements a new modal that explicitly shows the new client secret when hashing is enabled. This is done in the same fashion as the personal access token.
I've also added a note to the upgrade guide that people should re-publish the Vue assets every time they upgrade.
> [9.x] Implement secret modal

- UPGRADE.md
The config values included in passport.php don't match those shown in the upgrade guide for personal access tokens in v9.1. This matches the values with those in the config file.
> Match name of personal access token methods to config

- config/passport.php
- database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
- database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php
- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
- src/AuthCode.php
- src/Client.php
- src/PersonalAccessClient.php
- src/RefreshToken.php
- src/Token.php
- tests/Feature/PassportTestCase.php
This PR introduces configuration for model connection. It is working the same way as [Laravel Telescope Connection Config](https://github.com/laravel/telescope/blob/3.x/config/telescope.php#L47-L52).
This required when your database with OAuth server is working not on default connection.
Not a breaking change because models use `$connection` property as a fallback value.
> [9.x] Allow to change Models database connection

- src/Bridge/AuthCodeRepository.php
`Laravel\Passport\Bridge\AuthCodeRepository` currently uses the `setRawAttributes` method to populate a model when saving an auth code.
This PR replaces that with `forceFill`, to ensure that accessors & mutators are executed before saving.
I couldn't find any tests that test this particular bit of code. If I missed them, I'm happy to add tests for it.
Fixes #908
> [10.x] Change to forceFill

- src/Token.php
When the user model does not have the primary key as "id" the relationship does not work, I left it in a way where the primary key is dynamic.
> Nonstandard ID in the token's relationship with the user

- src/Passport.php
In the `Passport::actingAsClient()` method, sets the Token's `client_id` attribute and a proper `client` relationship instead of simply setting a `client` attribute. This mirrors the expected Eloquent behavior.
> Fix actingAsClient token relation

- src/PassportServiceProvider.php
Fix typo doc param `$key` to `$type`
> Fix typo on param doc

- src/Console/InstallCommand.php
I open this PR for two reasons:
1. Here is the hope to change `client_uuids` to `true`, instead of change all `false` to `true`.
2. The user cannot know which configuration item was changed by this code.  
Thanks.
> [9.x] Improve `passport:install` command

- src/Http/Controllers/ClientController.php
- src/Http/Controllers/PersonalAccessTokenController.php
- tests/Unit/ClientControllerTest.php
- tests/Unit/PersonalAccessTokenControllerTest.php
Fixes https://github.com/laravel/passport/issues/1299
> [9.x] Fix maxlength for token names

- src/Console/PurgeCommand.php
Purge command is currently not using models set by:
- `\Laravel\Passport\Passport::useAuthCodeModel($authCodeModel)`
- `\Laravel\Passport\Passport::useTokenModel($tokenModel)`
- `\Laravel\Passport\Passport::useRefreshTokenModel($refreshTokenModel)`
This PR is making sure these are used as a user might expect.
> [9.x] Use custom models in purge command if set

- resources/js/components/AuthorizedClients.vue
- resources/js/components/Clients.vue
- resources/js/components/PersonalAccessTokens.vue
Tables on vue component is not responsive when it comes to smaller devices. Adding `table-responsive` on table class.
Files changes on 
- AuthorizedClients.vue
- Clients.vue
- PersonalAccessTokens.vue
From `"table table-borderless mb-0"` to `"table table-responsive table-borderless mb-0"`
This PR is making sure table row is scrollable and responsive.
> Apply table responsive on table class

- src/ClientRepository.php
- src/Passport.php
- src/PassportServiceProvider.php
- src/PersonalAccessTokenFactory.php
This PR removes the old and now redundant way to set the personal access client ID and secret. This will make the install step here a bit easier: https://laravel.com/docs/7.x/passport#creating-a-personal-access-client
The only breaking change and upgrade step is to remove these methods from the app's `AuthServiceProvider`.
> [10.x] Remove old static personal client methods

- composer.json
- tests/Unit/AuthorizationControllerTest.php
For some reason Passport required Guzzle as a dependency even though the only Guzzle namespace mention in the entire codebase was in just one test (the Guzzle PSR 7 response class). So I've changed that to use the Nyholm PSR 7 response which is also required by Passport (and recommended by Symfony PSR HTTP bridge) and in doing so I've removed the entire Guzzle dependency.
> [9.x] Remove Guzzle dependency

- .github/workflows/tests.yml
I've updated the major versions of the actions that were being used. No other changes were needed as there was no breaking changes (for the syntax that Passport uses).
> [9.x] Use newer Github actions

- composer.json
This will allow us to test Passport 9 with PHP 8 after the support for it lands in the framework repository.
> [9.x] Allow PHPUnit 9

- src/Passport.php
My IDE for some reason for this function only reports some strange chars. Looks like it was the nbsp; space vs a literal one. Looks like thats just how it was when it was added.
Original add: https://github.com/laravel/passport/commit/66add573c238307392a7e481a9151ae210193476#diff-f21ed80d2b094fcf734f3ca855cffc0b
> Use proper spaces for docblock - actingAsClient

- database/factories/ClientFactory.php
- tests/Feature/AccessTokenControllerTest.php
Just wanted to add some tests as Passport is way more than Password Grant now.
The 10.x/master iteration of https://github.com/laravel/passport/pull/1340
> [10.x] Client Credentials Feature tests

- tests/Unit/AccessTokenControllerTest.php
- tests/Unit/ApproveAuthorizationControllerTest.php
- tests/Unit/AuthorizationControllerTest.php
- tests/Unit/AuthorizedAccessTokenControllerTest.php
- tests/Unit/BridgeAccessTokenRepositoryTest.php
- tests/Unit/BridgeClientRepositoryTest.php
- tests/Unit/CheckClientCredentialsForAnyScopeTest.php
- tests/Unit/CheckClientCredentialsTest.php
- tests/Unit/CheckForAnyScopeTest.php
- tests/Unit/CheckScopesTest.php
- tests/Unit/ClientControllerTest.php
- tests/Unit/DenyAuthorizationControllerTest.php
- tests/Unit/HandlesOAuthErrorsTest.php
- tests/Unit/PassportTest.php
- tests/Unit/PersonalAccessTokenControllerTest.php
- tests/Unit/TransientTokenControllerTest.php
- Using the `assertSame` to replace `assertEquals` and it can make assertion equals checking strict.
> Using assertSame to make assertion equals strict

- README.md
Shields.io works a lot better than the old pugx.org.
> [10.x] Update the badges to use shields.io

- .github/workflows/tests.yml
- composer.json
- phpunit.xml.dist
- src/Http/Controllers/AccessTokenController.php
- src/PassportServiceProvider.php
- src/PersonalAccessTokenFactory.php
- tests/Feature/AccessTokenControllerTest.php
- tests/Unit/PersonalAccessTokenFactoryTest.php
Currently blocked by https://github.com/thephpleague/oauth2-server/pull/1146
> [8.x] PHP 8 Support

- .github/workflows/tests.yml
- composer.json
- phpunit.xml.dist
- src/PassportServiceProvider.php
- src/PersonalAccessTokenFactory.php
- tests/Feature/AccessTokenControllerTest.php
- tests/Unit/PersonalAccessTokenFactoryTest.php
This provides support for PHP 8 so people on Laravel 6 LTS can still install Passport. ~Unfortunately this requires the dropping of PHP 7.2 support because OAuth2 Server v8.2 dropped it as well.~
~An alternative solution to the issues for people on Laravel 6 LTS and keep PHP 7.2 support is to constrain `lcobucci/jwt` to `<=3.3.` but that then we won't be able to offer PHP 8 support on Passport 9.~
~@taylorotwell I'll leave it up to you to decide on this.~
Thanks to @Sephster PHP 7.2 was re-added to OAuth2 Server 8 🎉
> [9.x] Support PHP 8.0

- src/Console/PurgeCommand.php
- tests/Feature/Console/PurgeCommand.php
The `passport:purge` command does a good job of removing revoked and expired tokens in the different tables, but we end up with lots of invalid refresh tokens pointing to non-existing access tokens. This PR adds purging of invalid refresh tokens to the command as well. Also added a test class for this command.
> [10.x] Add purging of invalid refresh tokens to command

- composer.json
- src/Console/KeysCommand.php
- tests/Unit/KeysCommandTest.php
There is technically a breaking change here for people people overwriting the `handle` method of the `KeysCommand`. I had to remove it because `RSA` is an abstract class in v3. I believe in reality there aren't many people who would be overwriting this command. phpseclib was first introduced in https://github.com/laravel/passport/pull/72 which adds the `RSA` class to the handle method but it's unclear why that was done. I cannot imagine anyone would want to swap it out.
Closes https://github.com/laravel/passport/issues/1409
> [10.x] Update to phpseclib v3

- config/passport.php
- database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
- database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php
- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
- src/AuthCode.php
- src/Client.php
- src/PersonalAccessClient.php
- src/RefreshToken.php
- src/Token.php
- tests/Feature/PassportTestCase.php
This PR reverts https://github.com/laravel/passport/pull/1255. In hindsight that probably wasn't the best choice as it's [breaking some default Laravel behavior like the `--database` flag on the migration command](https://github.com/laravel/passport/issues/1370). This also causes Passport to differ from any other Laravel first party package (except Telescope). 
The problem that the PR wanted to solve can better be solved imo by overwriting the default models as explained here: https://laravel.com/docs/8.x/passport#overriding-default-models. In combination with [customizing the migrations](https://laravel.com/docs/8.x/passport#migration-customization) this already allows people to do whatever they want. I believe this is a more sensible approach to also keep the package straightforward and …
> [11.x] Revert model DB connection customization

- composer.json
- src/Console/KeysCommand.php
This PR backports support for phpseclib v2 who are stuck on it due to 3rd party dependencies (like Flysystem v1's SFTP adapter).
See https://github.com/laravel/passport/issues/1416
> [10.x] Backport phpseclib v2

- src/Events/AccessTokenCreated.php
The `$user_id` may be `int` and `null`.  
for example:  
The `$user_id` may be an `int` when using password grant.
The `$user_id` is `null` when using client grant.
> Fix `$userId` type

- src/Token.php
- tests/Unit/BridgeAccessTokenRepositoryTest.php
This PR removes the timestamp override on the Token model. I couldn't see any implications on this or reasoning why it was disabled in the first place.
Related issues/PRs:
- https://github.com/laravel/passport/pull/1411
- https://github.com/laravel/passport/issues/786
- https://github.com/laravel/passport/pull/787
- https://github.com/laravel/passport/pull/1075
> [11.x] Allow timestamps on Token model

- src/Guards/TokenGuard.php
One select from oauth_access_tokens and one from oauth_clients less. The issues mentioned in #382.
Before:
```
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_clients` where `id` = ? limit 1
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_clients` where `id` = ? limit 1
```
After:
```
select * from `oauth_access_tokens` where `id` = ? limit 1
select * from `oauth_clients` where `id` = ? limit 1
select * from `oauth_access_tokens` where `id` = ? limit 1
```
as you see there's still one redundant query, but it might be harder to get rid of it.
> [11.x] Improve authenticateViaBearerToken() performance

- composer.json
- tests/Unit/PassportServiceProviderTest.php
This PR changes the fake keys in Passport's test suite to use valid openssl generated keys. This change is required because the League's OAuth 2 server now validates keys using the openssl lib.
Previously keys were validated using basic regex matching. Keys are generated on the fly in this PR. It has negligible effects on runtime of tests but if you'd prefer hardcoded keys let me know. Cheers.
> [10.x] Use Real Keys in Tests

- tests/Feature/AccessTokenControllerTest.php
- tests/Unit/PassportServiceProviderTest.php
This PR fixes tests in Passport that are broken due to small changes in the latest OAuth 2 server release. Namely:
* The invalid password error message has been made clearer. Previously this function set a blank string hint but now the hint is not set at all as the message is clear enough. Fixed the test so that we don't check for the hint key in the returned array from the exception
* Keys are no longer saved as files in the OAuth 2 server. If you passed an key as an in-memory key previously, we would save this as a file in the /tmp dir. There isn't really a need to do this as an in memory key is fine. I've tweaked a broken test to take note of this change.
> Fix tests failing due to latest OAuth 2 server release

- src/Guards/TokenGuard.php
- src/PassportServiceProvider.php
- tests/Unit/TokenGuardTest.php
Fixes #882 
This PR allows developers to retrieve the currently authenticated client from the guard, this functionality was already present but inaccessible due to the guard being wrapped in another guard.
Tests all still work (I had to move some stuff around because request is now getting passed through the constructor, but I didn't functionally change any tests).
What this PR changes:
- Turns `TokenGuard` into an actual guard, implementing the `Guard` interface
- Removes the wrapped `RequestGuard`, instead `TokenGuard` is now used as is
A lot of the non-public methods on `TokenGuard` still take `$request` as an argument, which could be removed in favor of `$this->request`. I opted not to do this to keep the PR as small as possible
> [11.x] Allow authenticated client to be retrieved from the guard

- src/PassportServiceProvider.php
Using `PHP 8.1.0`
```
str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/vendor/laravel/passport/src/PassportServiceProvider.php line 268
```
> Fix str_replace error when third parameter ($subject) is null

- src/Bridge/Scope.php
Using PHP 8.1.0, passport 10.2.1 and running behat tests: 
```
During inheritance of JsonSerializable: Uncaught Behat\Testwork\Call\Exception\CallErrorException: 8192: 
Return type of Laravel\Passport\Bridge\Scope::jsonSerialize() should either be compatible with 
JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be 
used to temporarily suppress the notice in /var/www/vendor/laravel/passport/src/Bridge/Scope.php
line 28 in /var/www/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php:90
```
> fix: Internal method return types, php 8.1 tests compatibility

- src/Passport.php
- src/PassportServiceProvider.php
- tests/Feature/AccessTokenControllerTest.php
**league/oauth2-server** supports custom response type [https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationServer.php#L103](https://github.com/thephpleague/oauth2-server/blob/master/src/AuthorizationServer.php#L103).
This pull request add possibility to override default "BearerTokenResponse" to custom schema (for example to add new extra parameters to support OpenID Connect flow...).
To override response need add to service provider:
```php
Passport::$authorizationServerResponseType = new CustomResponse();
```
> [10.x] Allow to use custom authorization server response

- src/Guards/TokenGuard.php
- src/Passport.php
- tests/Feature/ActingAsClientTest.php
This PR changes the `Passport::actingAsClient()` method. Currently when stubbing the client via Passport, the guard doesn't actually reflect the stub:
```php
>>> $client = Laravel\Passport\Database\Factories\ClientFactory::new()->createOne()
=> Laravel\Passport\Client {#4807}
>>> Laravel\Passport\Passport::actingAsClient($client)
=> Laravel\Passport\Client {#4807}
>>> auth()->guard('api')->client()
=> null
```
After this PR the following happens:
```php
>>> $client = Laravel\Passport\Database\Factories\ClientFactory::new()->createOne()
=> Laravel\Passport\Client {#4807}
>>> Laravel\Passport\Passport::actingAsClient($client)
=> Laravel\Passport\Client {#4807}
>>> auth()->guard('api')->client()
=> Laravel\Passport\Client {#4807}
```
This makes `Passport::actingAsClient()` behave similar to …
> [11.x] Stub client on guard when calling Passport::actingAsClient()

- UPGRADE.md
I just went through the steps of upgrading passport from v8 to v10 and hit a minor snag that could have been solved by a tweak to the documentation.
When upgrading from v8 to v9 it says place two Passport static calls "within the `boot` method of your `AppServiceProvider`"
When upgrading from v9 to v10 it says you can remove the calls from your `AuthServiceProvider`.
I don't claim to know where those calls belonged in the first place, so this proposal just updates the documentation to list them both.
> Minor documentation tweak to UPGRADE.md

- database/factories/ClientFactory.php
When using this factory in feature tests with `$this->withoutDeprecationHandling();` call the test fails as the deprecation gets converted to an exception:
```
Since fakerphp/faker 1.14: Accessing property "company" is deprecated, use "company()" instead.
```
https://github.com/FakerPHP/Faker/pull/164
> [10.x] Fix Faker deprecations

- composer.json
- src/ApiTokenCookieFactory.php
- src/Guards/TokenGuard.php
- tests/Unit/TokenGuardTest.php
The firebase/php-jwt package recently had to make breaking changes to resolve a security flaw in their library. This change upgrades that library and fixes the code that broke with the upgrade.
You can find more information about the fixes to the firebase/php-jwt here:
https://github.com/firebase/php-jwt/releases/tag/v6.0.0
https://github.com/firebase/php-jwt/issues/351
https://security.snyk.io/vuln/SNYK-PHP-FIREBASEPHPJWT-2434829
Hope this helps! Let me know if there's something else I can do to get this merged. Thanks! 😄
> Upgrade firebase/php-jwt to ^6.0

- src/Http/Rules/RedirectRule.php
- src/Http/Rules/UriRule.php
Fixes https://github.com/laravel/passport/issues/1542
This PR add the support for URI e.g. `scheme://home-mobile` in `redirect` field for `\Laravel\Passport\Client`.
> [10.x] Add new URI Rule to validate URI and use it to RedirectRule.

- src/Passport.php
- tests/Feature/ActingAsTest.php
Redo of [#1548](https://github.com/laravel/passport/pull/1548), this time targeting master:
> Fixes #1138 
>
> This fixes the issue of inherited scopes not working with `Passport::actingAs()`, by not mocking the Token model and just passing a real one with the requested scopes. I couldn't find any reason as to why the model is currently mocked, and all the tests still seem to pass fine.
>
> (PS. When will Passport 11 be released? Passport did not get a new major when Laravel 9 came out, is there some stuff that still needs to be done?)
> [11.x] Fix scope inheritance when using Passport::actingAs()

- .github/workflows/tests.yml
- composer.json
Dropping legacy PHP and Laravel versions in preparation for the next release.
> [11.x] Drop PHP 7.x and Laravel v8

- src/Passport.php
This PR removes the old deprecated expiration properties from Passport. These were superseded in https://github.com/laravel/passport/pull/1500 and probably are never reference directly.
> [11.x] Remove deprecated properties

- composer.json
- src/Http/Controllers/AccessTokenController.php
- src/PersonalAccessTokenFactory.php
- tests/Feature/AccessTokenControllerTest.php
- tests/Unit/AccessTokenControllerTest.php
I wanted to drop JWT v3 as well but given that `league/oauth2-server` still allows for it I guess it's best to wait until they drop it.
> [11.x] Remove deprecated functionality and simplify some feature tests

- src/Console/PurgeCommand.php
For some deploys, especially big projects/companies with a lot of traffic, the default days in passport:purge command is not enough. 
The solution is setting a --days and --hours parameter, to set the custom times. By default the behaviour is not changing and still being the default 7 days
> [11.x] Custom days and hours to passport purge command

- src/Passport.php
- src/PassportServiceProvider.php
Passport's bootstrapping of routes was changed recently (https://github.com/laravel/passport/pull/1464), this PR aims to make it a little easier for developers to disable the routes that ship with Passport (which currently requires disabling its service provider and replacing it with a custom one).
PS. I lifted this code from Fortify
> [11.x] Allow for bootstrapping without loading routes

- src/Http/Controllers/AuthorizationController.php
- tests/Unit/AuthorizationControllerTest.php
Related to #1389 
Let's assume we have a 3rd-party app that uses our API via authorization code grant (w/ or w/o PKCE) and a user that is signed in on several devices (i.e. has already several valid tokens) tries to switch his account (logout on the 3rd-party app and sign-in with a different account). 
Currently **it is impossible**, because after he logs out (we revoke the current token) and wants to login again (we redirect to authorization route), the user is automatically signed in again, which leads to a **dead-loop UX**.
In most authorization servers, there is a `prompt` parameter that specifies whether the authorization server prompts the user for reauthentication and consent. The most common `prompt` values are `none`, `login` and `consent`.
This PR implements the `prompt=consent` …
> [11.x] Support prompting re-consent when redirecting for authorization

- src/Http/Controllers/ApproveAuthorizationController.php
- src/Http/Controllers/DenyAuthorizationController.php
- src/Http/Controllers/RetrievesAuthRequestFromSession.php
- tests/Unit/DenyAuthorizationControllerTest.php
This PR uses OAuth2 server to handle denying the authorization request instead of manually generating the redirect response. The OAuth2 Server handles the `access_denied` status and also sets a proper `error_description` in the returned query string for both implicit and authorization code grants.
This PR also fixes another minor issue; Every call to OAuth2 server is wrapped by `HandlesOAuthErrors` but it wasn't the case on `ApproveAuthorizationController`; It is handled now.
> [11.x] Let OAuth2 server handle the denying response

- routes/web.php
- src/Http/Controllers/AuthorizationController.php
- src/PassportServiceProvider.php
- tests/Unit/AuthorizationControllerTest.php
According to #1571, This PP also binds `StatefulGaurd` to the default auth guard (same as before using `auth` middleware on the route).
The same approach is already used on Laravel Fortify: https://github.com/laravel/fortify/blob/ebc9045ef7bd2a2a37d54dde9c5df7d1b9d48780/src/FortifyServiceProvider.php#L61-L63
----
Related to #1389
As explained on #1567 and in addition to #1569, this PR adds support for `prompt=login` that causes the authorization server to display the login page first.
This PR also causes `prompt=none` to return an error if the user is not already authenticated instead of prompting the login page, which is the expected behavior (to prompt nothing).
> [11.x] Support prompting login when redirecting for authorization

- src/ClientRepository.php
A client's ID can also be a string when using UUIDs, this PR updates some doc blocks to reflect this.
> [11.x] Fix ClientRepository doc blocks

- config/passport.php
- routes/web.php
Related to #1602, We have already defined and used `passport.guard` config here: https://github.com/laravel/passport/blob/662325a90b8c3184c548eaf66ce971925f2b90dc/src/PassportServiceProvider.php#L140-L141
This PR adds a default value for `guard` to `config/passport.php` and also uses this guard on predefined Passport routes. This change is totally backward compatible and if `passport.guard` is not defined or `null`, the Passport will use `auth.defaults.guard` config value by default.
PS: The same approach is used on Fortify:
- https://github.com/laravel/fortify/blob/eb97f088c2a3e010e76cb58e9406427d1cee8de3/routes/routes.php
- https://github.com/laravel/fortify/blob/eb97f088c2a3e010e76cb58e9406427d1cee8de3/config/fortify.php#L6
> [11.x] Add auth guard to routes

- src/Http/Controllers/AuthorizationController.php
- src/TokenRepository.php
- tests/Unit/AuthorizationControllerTest.php
This is not a breaking change, fixes #1616 and fixes #1609. This PR fixes the authorization issue for those who want to use a non-default guard when customizing the `passport.guard` config param.
PS: This also fixes some doc blocks.
> [11.x] Get authenticated user from the guard

- src/Console/ClientCommand.php
We get a fair amount of confused passport users on the laravel discord wondering what this user_id is even for. It might help to indicate that the input is optional.
> Update ClientCommand.php's user_id description

- src/HasApiTokens.php
Fixes an incorrect doc block, this is currently already used this way in Passport:
https://github.com/laravel/passport/blob/3ac7b1e8f9814e47af5a9d5ab88c415060d5c782/src/Guards/TokenGuard.php#L258
PS. I think a common interface should be introduced for `Token` and `TransientToken` so the user's token can be typed properly across the board, but that should probably go to master as it is a bigger change
> [11.x] Fix doc block for `withAccessToken()`

- resources/views/authorize.blade.php
- src/ClientRepository.php
- src/Console/ClientCommand.php
- src/Passport.php
- src/PersonalAccessTokenFactory.php
- tests/Feature/AccessTokenControllerTest.php
- tests/Unit/PersonalAccessTokenFactoryTest.php
PR of the change presented here:
https://github.com/laravel/passport/issues/1624
This PR has the purpose of modifying the way that the oauth Client model is obtaining its primary key.
For most people it won't have any impact, for some people who use another column as the primary key (instead of ID) it will be fixed in this flow.
> [11.x] Get model PK instead of forcibly id column

- src/HasApiTokens.php
Followup for #1620, forgot to update the docs in other places where the same token is referenced.
Passport sets the token to a transient token here:
https://github.com/laravel/passport/blob/3ac7b1e8f9814e47af5a9d5ab88c415060d5c782/src/Guards/TokenGuard.php#L258
> [11.x] Indicate current token can be `TransientToken`

- src/Guards/TokenGuard.php
- src/Passport.php
- tests/Unit/TokenGuardTest.php
This PR adds a new option to Passport to not decrypt the JWT cookie when authenticating.
Currently when dealing with the JWT cookie Passport's behaviour is this:
- When creating the JWT cookie, Passport expects the `EncryptCookies` middleware to be active, and relies on it for encryption
- When reading the JWT cookie, Passport expects the `EncryptCookies` middleware to be inactive, it decrypts the cookie on its own
Because of this, implementing a middleware similar to Sanctum's [EnsureFrontendRequestsAreStateful](https://github.com/laravel/sanctum/blob/3.x/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php) is currently not possible, as it will cause the JWT token to be decrypted twice.
Note that this PR does not contain any breaking changes, Passport's current behaviour stays the …
> [11.x] Add support for `EncryptCookies` middleware

- src/Exceptions/AuthenticationException.php
- src/Http/Controllers/AuthorizationController.php
- src/Http/Middleware/CheckClientCredentials.php
- src/Http/Middleware/CheckClientCredentialsForAnyScope.php
- src/Http/Middleware/CheckCredentials.php
- src/Http/Middleware/CheckForAnyScope.php
- src/Http/Middleware/CheckScopes.php
- tests/Unit/AuthorizationControllerTest.php
- tests/Unit/CheckClientCredentialsForAnyScopeTest.php
- tests/Unit/CheckClientCredentialsTest.php
- tests/Unit/CheckForAnyScopeTest.php
- tests/Unit/CheckScopesTest.php
After looking for an easy way to tap into Passport's behaviour to manipulate the destination path when unauthenticated, I found there wasn't a particularly clear route to do so.
When an authentication error occurs, the script simply throws an `Illuminate\Auth\AuthenticationException`, the same as any other authentication section within a Laravel project. When this generic is thrown, it's caught by the exception handler and simply redirected to `route('login')`.
I felt it'd be useful to have a simpler way to tap into this functionality and customise the redirect behaviour.
To achieve this, I've simply created Passport's own AuthenticationException class that anyone can then catch further up the chain and then perform the logic required for their specific use case.
In my use case, I'll be …
> [11.x] Move AuthenticationException into the scope of Laravel Passport

- src/Token.php
- Passport Version: 11.7.0
- Laravel Version: 10.0.3
laravel 10 update:
passport token model problem:
> laravel10 The Eloquent model's deprecated $dates property has been removed.

- database/migrations/2016_06_01_000001_create_oauth_auth_codes_table.php
- database/migrations/2016_06_01_000002_create_oauth_access_tokens_table.php
- database/migrations/2016_06_01_000003_create_oauth_refresh_tokens_table.php
- database/migrations/2016_06_01_000004_create_oauth_clients_table.php
- database/migrations/2016_06_01_000005_create_oauth_personal_access_clients_table.php
I'm fairly sure this won't get merged, and I'm cool with that... but encountered an issue today where [recent changes made to Laravel 9](https://github.com/laravel/framework/pull/46073) have broken in memory tests when using anonymous migrations written in this style, as reported [here in Telescope](https://github.com/laravel/telescope/pull/1304).
I've aimed this PR at Passport v10, which is otherwise compatible with Laravel 9, and attempted to write it in a similar style to [Nuno's fix for the aforementioend Telescope issue](https://github.com/laravel/telescope/pull/1305)... but also know that a better fix is just to upgrade to Passport v11.
Hope this helps... and, even if it doesn't get merged, I hope it helps anyone else who bumps into the same problem.
✌️
> [10.x] Fix migrations for Laravel 9.x

- src/Bridge/AccessTokenRepository.php
- src/Passport.php
Related to #94, #1637, This PR allows overriding the `Laravel\Passport\Bridge\AccessToken` class by calling `Passport::useAccessTokenEntity`.
This class has `convertToJWT` method that can be overridden to add custom claims to JWT token, as there seems to be no other way to do this atm.
PS: It may be even more convenient after this: thephpleague/oauth2-server#1328
> [11.x] Allow overriding the `AccessToken` class

- src/ClientRepository.php
Since `createPersonalAccessClient` and `createPasswordGrantClient` are both called with `null` as the `$userId` and the migrations support this, it would be good to have the docblock in-line with the actual usage of the code.
I'm trying to set up a personal access client in my tests to issue API tokens, and this docblock is incorrect.
> Make `$userId` nullable in `ClientRepository->createPersonalAccessClient`

- src/RefreshToken.php
Use `casts` instead of `dates` property.
> [11.x] Removed deprecated `dates` property from `RefreshToken` model

- src/AuthCode.php
Use `casts` instead of `dates` property.
> [11.x] Removed deprecated `dates` property from `AuthCode` model

- src/ClientRepository.php
- src/Console/ClientCommand.php
- src/Console/InstallCommand.php
This PR adds support for provider guards in the `ClientRepository` class of Laravel Passport for creating Personal Access Clients. The provider guard functionality allows developers to authenticate users using any provider they choose, or any custom provider.
The implementation involves adding a `provider` parameter to the `createPersonalAccessClient` method in the `ClientRepository` class. If the parameter is specified, the authentication will be done using the specified provider guard. If the parameter is not specified, the authentication will be done using the default provider guard.
This feature is useful for developers who want to use a custom authentication provider in their applications while still being able to create Personal Access Clients in Laravel Passport. It also allows for …
> [11.x] Add Provider Guard to ClientRepository for Personal Access Clients

- database/factories/ClientFactory.php
This allows tools like PHPStan and PHPStorm to understand what object is created by this factory
> Add generics to client factory

- src/Client.php
- src/ResolvesInheritedScopes.php
- src/Token.php
- tests/Unit/BridgeScopeRepositoryTest.php
This PR is a minor improvement to #1682.
This PR makes scope inheritance work with limiting scope access for clients.
As an example, let's say we have the following scopes:
```text
user       update the user's info
user:read  read the user's info
```
And we have the following client:
```php
Passport::$withInheritedScopes = true;
$client = new Client();
$client->scopes = ['user'];
```
Before this PR: The `user:read` scope cannot be granted to the client, because the client doesn't have access to it
After this PR: Both of the scopes can be granted to the client if requested
> [11.x] Add support for inherited scopes when limiting scopes on clients

- src/Bridge/ScopeRepository.php
- tests/Unit/BridgeScopeRepositoryTest.php
This fixes a breaking change introduced by #1682
> [11.x] Allow scope repository to be constructed without parameters

- src/Http/Middleware/CheckCredentials.php
- src/Http/Middleware/CheckForAnyScope.php
- src/Http/Middleware/CheckScopes.php
- src/Http/Middleware/CreateFreshApiToken.php
- tests/Feature/ActingAsTest.php
This PR introduces a more "typed" API for all the first-party middleware - which gives a nicer DX than the "stringy" API, in my opinion.
> [11.x] Named static methods for middleware

- src/HasApiTokens.php
Small PHPDoc fix to allow the following
```php
$user->withAccessToken(null);
```
https://github.com/laravel/passport/blob/6dab7d087ef933d6ca4cc0038d10571d8a886b8a/src/HasApiTokens.php#L9-L14
> [11.x] Allow unsetting a user's access token

- src/Client.php
Since Laravel v10.40, Eloquent strict mode throws an error because "grant_types" does not exist on the Client model. This is caused by https://github.com/laravel/framework/pull/49480. By adding a getter-method for the attribute, the error disappears
> [11.x] Add getGrantTypesAttribute method to fix Eloquent strict mode error

- src/Client.php
- src/PassportServiceProvider.php
I noticed while developing an internal package where I pre-configure Passport from the `boot` method of a service provider that there were some inconsistencies. 
In some places `config('passport.client_uuids')` is used while in other places `Passport::clientUuids()` is used.
Because I only used `Passport::setClientUuids(true)` this resulted in an error due to the uuid not being set in the creating event.
> Consistently retrieve client uuids value from Passport

- src/Passport.php
- src/PassportServiceProvider.php
The password grant type (a.k.a. Resource Owner Credentials grant type) is no longer recommended for use, due to user credentials having to be handled by a client directly. It, alongside the implicit grant type, has been omitted from the [OAuth 2.1 RFC](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-10) (which is still in draft).
This PR allows developers to easily disable this grant type within Laravel Passport. Its still enabled by default for backward compatibility purposes, but should probably default to disabled in the next major version of Passport
> [11.x] Allow developers to disable the password grant type

- UPGRADE.md
- src/Passport.php
- tests/Feature/AccessTokenControllerTest.php
Related to #1712. This PR disables Password grant by default.
Update Docs PR: laravel/docs#9318
> [12.x] Disable password grant by default

- src/Client.php
This PR changes the visibility of the client plain secret to public. Due to the accessor that is present on the client model this property is already public for reading, but static analysis tools like PHPStan don't recognize this.
> [12.x] Make `Client::$plainSecret` public

- src/Console/KeysCommand.php
- src/Passport.php
- src/PassportServiceProvider.php
- tests/Unit/PassportServiceProviderTest.php
Passport currently does not check filesystem permissions of the keys it uses, per https://github.com/laravel/passport/pull/454. Passport also doesn't set the correct permissions on the keys it creates.
This PR aims to have Passport use more secure permissions by default, whilst still allowing developers to opt out.
Passport will now:
- Automatically use stricter permissions when creating keys through the `passport:keys` command
- Check key permissions before using them
- This may be toggled off by setting `Passport::$checkKeyPermissions` to `false`
- This check is disabled on Windows, because it does not support this
> [12.x] Use more secure key permissions

- src/Client.php
Calling `isset` on a property that doesn't exist triggers strict mode violations.  We should check that the attribute isset exists instead.
> Check that properties `grant_types` and  `scopes` exist
